### ISSUE TITLE
Did you tested it on speeds like 200/500/1000 Megabits/s?

### ISSUE THREAD

**Issue by alexeychikk** [adolfintel/speedtest#1]

**Comment by adolfintel** [comment]
In theory it works, but the server that currently hosts my site can maybe reach 70-80 mbit/s

**Comment by alexeychikk** [comment]
I am developing speedtest. And my main problem that it doesn't work speeds like 200/500/1000 Megabits/s in one thread.

**Comment by adolfintel** [comment]
Well on my website I noticed that on very slow computers the speed is limited by the framerate of the animated background. I suppose the same thing is happening to you. Several DOM events seem to be tied to the rendering of the page.
That said, here's a couple of things you can try:
-If you can configure your server, make it send bigger chunks so the update events on the client are triggered less often
-Try to use Web Workers. It's a bit of a pain, and I don't think all browsers map them to actual threads but it's probably enough to decouple it from the rendering of the page, thus removing this issue completely.

**Comment by alexeychikk** [comment]
I have access to 1Gbps Amazon server with the ability to limit speed. Unfortunately your example doesn't work on high speeds.

**Comment by adolfintel** [comment]
I guess that's the problem then, it's limited by the rendering. I will try to make a new version of this Speed Test using Web Workers and see if it's any better
