### ISSUE TITLE
Is there some way to make the upload test run longer?

### ISSUE THREAD

**Issue by bcacbe** [adolfintel/speedtest#10]
Is there some way to make the upload test run longer? When testing on a 200/200 Mbps connection the upload test runs too fast (it ends within a second or two of starting) not giving enough time to ramp up.

Also wanted to report two other issues;

Under iphone browser upload test is inaccurate showing 300 Mbps+ on a connection with only 10 Mbps.
Ping test seems inaccurate no matter the browser or system using example4.

**Comment by adolfintel** [comment]
Yes, in example4.html at line 80 you can change the duration of the tests
