### ISSUE TITLE
On Linux: download=Upload=1Gbit, on Windows10 download=0.5Mbit, upload=320 Mbit

### ISSUE THREAD

**Issue by mesmariusz** [adolfintel/speedtest#104]
Hi. 

Because I have very well experiences with LAMP package (WWW server) on Linux i decided to install WinLAMP ( http://winlamp.sourceforge.net/ ) packages also on my home machines running on Win10. 
My goal was to run speedtest-html5 on every home machine to make it possible easy and simple connecttion speed measurements between every two machines in the network. That's why I decided to WinLAMP (easy to install and enough to run speedtest-html5). 

Finally I have now speedtest-html5 run on a few machines running on Win10+WinLAMP ond on a one machine runing on Linux Mint + LAMP.

When I enter from any machine in the network to speedtest-html5 running on Linux Mint my measurements shows properly Gigabit LAN connection speed: 

https://obrazki.elektroda.pl/6533567500_1516490479.png

But when I enter from any machine in the network to speedtest-html5 running on Win10 my measurements shows download decreased to 0.5 Mbit and upload decreased to 320 Mbit

https://obrazki.elektroda.pl/2702046900_1516490498.png

I'm wondering if the reason is that Apahe2 controls also download / upload by itself?  
Or maybe this is a specific Windows 10 behavior?

Machine with Linux Mint shows proper results with no any issues.

Do you have any idea how could I  solve my issue?

Thank you and best regards
Mariusz

**Comment by adolfintel** [comment]
Hi Mariusz,
That looks like a config issue, or maybe openssl missing. If you don't want to tinker with config stuff, download XAMPP for windows, it has everything you need

**Comment by tomaszkrzyzanowski** [comment]
This winlamp is very old thing, try XAMPP - it is at least still supported and have much newer packages
