### ISSUE TITLE
Epiphany 3.8.2 from Raspbian 7.11 doesn't send an Accept-Language header

### ISSUE THREAD

**Issue by nschmalenberger** [adolfintel/speedtest#106]
I have a Raspberry Pi at a remote office running Raspbian 7.11 with Epiphany 3.8.2, and it doesn't send any Accept-Language header in any request. The speed test works, but telemetry.php has a problem:
`[Fri Feb 02 14:02:00.096195 2018] [:error] [pid 3754] [client 212.161.13.153:31542] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/speedtest/telemetry.php on line 6, referer: http://example.com/speedtest/speedtest_worker.min.js`
After telemetry.php has this problem, no telemetry record gets stored.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html mentions that " If no Accept-Language header is present in the request, the server SHOULD assume that all languages are equally acceptable." so, its not a mandatory field. In case its not present, the other telemetry fields should still be kept.

**Comment by nschmalenberger** [comment]
I just learned, PHP 7 has the ?? operator that allows
`$ua=($_SERVER['HTTP_USER_AGENT'] ?? '');`
`$lang=($_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '');`

Which solves this issue for me (and also potentially for a missing user agent).
https://wiki.php.net/rfc/isset_ternary

**Comment by adolfintel** [comment]
Thanks for reporting the issue. I didn't expect it to crash the whole script for a missing header. I'll fix it ASAP.

**Comment by adolfintel** [comment]
I just committed the fixed telemetry.php
I've used ```isset``` instead of ```??``` for compatibility with PHP5. 
Also, I only checked ```$lang``` because there is no way any browser from this century doesn't specify the user agent.
