### ISSUE TITLE
Request - More optional tests

### ISSUE THREAD

**Issue by coolacid** [adolfintel/speedtest#107]
Would it be possible to add more of the tests optional? For example, I may not care so much about testing Upload/Download speeds for a VoIP related service, but I do care about ping and jitter. 

If this is already available to remove specific tests, I didn't see it in the docs (or a quick scan of the code)

In anycase, awesome project.

**Comment by adolfintel** [comment]
The feature is already present, you can start the test with a custom ```test_order``` parameter, to run only specific tests in a specific order. See doc.md for details. Once you've set that, if you're using one of my examples, remove the HTML for the test that you disabled.
