### ISSUE TITLE
ISO: Help (Have a similar project)

### ISSUE THREAD

**Issue by jdc20181** [adolfintel/speedtest#11]
Been trying to find a easy way to get a user's upload speed, I have a project that measures users internet speeds - Its Called SpeedTest as well (Long Name : BeffsBrowser's SpeedTest Project) 

Mind giving a hint on how to get a users upload speed? I read through your code, but some of it isn't easy to understand plus, mine is hosted here on github, so it is impossible to use php files. 

You can see the project's Source [Here](https://github.com/jdc20181/SpeedTest) 

And use it  [here](http://jdc20181.github.io/SpeedTest/) 

I think it would be pretty simple but, simply don't know. Currently I use a image on a seperate respo - to test the user's download speed, and now I am looking on how to do the same or similar to get a users upload speed. 

Thanks!

P.S. 

Other than it uses  php and other unfamilar stuff to myself, it is a good project, but has some flaws.

**Comment by adolfintel** [comment]
To test the upload speed, you have to send a large POST request and use the onprogress callback function to measure the speed (difference between event.loaded and its previous value, divided by the difference between the current timestamp and the previous timestamp).

If you want to use my test without PHP, all you have to do is replace garbage.php with a large file (there is one linked in the readme) and edit the example to replace garbage.php with the path to your large file relative to speedtest_worker.js
Note: your file should be incompressible if you want accurate results.
Note 2: no need to touch the upload test if you do this

Also, you said you found some flaws in my speedtest. What happened?

**Comment by jdc20181** [comment]
The flaws were accuracy. I know exactly where my speed should be (been
working on this project since July of last year or earlier) I use a variety
of testers to compare accuracy.once I did the test again it was more
accurate than the first time.

**Comment by adolfintel** [comment]
If you tested it from my site keep in mind that it's on a very cheap hosting (20€/year) so the speed is a bit limited and often jumps up and down

**Comment by jdc20181** [comment]
Ah- lol I use github to host my project but it is pretty accurate but (got
another developer question) sometimes It does what yours does (but after
the second time it is better) and sometimes it don't do it at all... the
next question is what do you use for your download speed as I explained (I
think I said this) I use a image then time it on how long it takes to load
it and then run it through a function (code is available just look at
'Main.js')

Thanks again for explaining :)

**Comment by adolfintel** [comment]
On my site I use garbage.php to generate random data. You can also use a large file of uncompressible data, like an mp4 video

**Comment by jdc20181** [comment]
Cool!

Again thanks for your help :)

**Comment by jdc20181** [comment]
So I don't have any unneeded code is there anything I can remove? I just need the Upload Speed Function

**Comment by jdc20181** [comment]
Update: I don't think this will work here on github - due to security restrictions.

**Comment by adolfintel** [comment]
Copy the ulTest function and call it manually

**Comment by jdc20181** [comment]
thanks. And also one last thing, couldn't get the big data .dat to work -  not really sure how to make it work...

Anyhow I will play with it see what i can come up with 👍
