### ISSUE TITLE
Wrong Ping Result

### ISSUE THREAD

**Issue by hadanin** [adolfintel/speedtest#118]
Hi adolftintel,

First of all, thanks for your great project!

I have read all solutions you have mentioned how to get a correct ping number, however I still have a problem with it. 

I have tried your project on our super fast server,since we are a big ISP company, also on a server we have hosted from speedtest.net.
In addition, I've enabled connection keep-alive, but still testing the project on different devices (Mobile, Tablet and desktop) from different locations and IPs in some browsers like:

1. mobile - Iphone 6S Safari(default browser)
2. Windows Firefox 

returns incorrect results. 

I have attached screen-shots of my tests to compare the results of both the project and speedtest.net in the same situation. 

The speedtest code is at: speedtest.ir, also These two links are the results in which you can check how different the ping numbers are. 

Correct One at speedtest.net: http://www.speedtest.net/result/6688999233
and the incorrect one resulted by the speedtest project: http://speedtest.ir/result.php?id=4268a5c70e0c05b19f7b924c04bf2a90

I would appreciate if you consider a solution to my current urgent problem. 

![correctping](https://user-images.githubusercontent.com/36588147/36349734-f062202a-14a0-11e8-91f2-2c65a31348a1.jpg)
![incorrectping](https://user-images.githubusercontent.com/36588147/36349747-ff2b1d8c-14a0-11e8-88d5-509e818e532f.jpg)

**Comment by adolfintel** [comment]
I just tested it from my devices and it looks correct. although I'm seeing a lot of lag caused by the ads you put in the test.

**Comment by hadanin** [comment]
Thank you for your answer, 

As I mentioned it does not work "sometimes" with the same situation(IP, Browser, Location).I had attached the wrong results which appeared for example twice in 10 times by running the project. 

However, we are an ISP company, so it is unacceptable by our customers. Additionally, every day, we have tones of dissatisfied customer calls why we have a huge difference between the real-time pings (or the results by speedtest.net) and the results of the project at speedtest.ir.
I have attached a screen-shot of my database records, so you can see the wrong ping results that we have got from the project like 360, 228 , ... .

Please try it more times and in different situations, to get what I mean.

Our effort is to make this project as a reference instead of speedtest.net for our large number of customers.

I would appreciate if you consider a solution.
![db_printscreen](https://user-images.githubusercontent.com/36588147/36374257-eea0dac6-157f-11e8-9b9f-335c8bcf9954.png)

**Comment by adolfintel** [comment]
Ammittedly, I have no idea what's causing the problem to you. The only way I can reproduce the problem (high ping and jitter) is if the browser is lagging really badly, and as you can see it involves a lot of different user agents so the cause is probably something else.
Is it possible that those ads you included in the page may contain a miner?

**Comment by hadanin** [comment]
Thank you for your attention, 

I have had this problem before enabling the ads too, however to show you; I disable them to have more new records which I attached a screen-shot of , below. 

![a](https://user-images.githubusercontent.com/36588147/36385850-123e2d70-15a9-11e8-9173-c706c7ad0fd1.png)

**Comment by adolfintel** [comment]
I don't know what else to suggest then, I'm sorry.
Try another speedtest project and see if you have the same problem.

**Comment by robingroppe** [comment]
I am seeing this too on my CentOS Server with pretty much stock Speedtest. 
For the first moment it looks slightly high but realistic and then for the second half of the pingtest the ping and jitter goes crazy.

https://rbn.gr/screens/1519400304-5b7230ee5908d0b9b9f297a734fd35cc98c36399.png

**Comment by adolfintel** [comment]
@robingroppe you have a pretty reasonable explaination, your server is throwing 404s at empty.php

**Comment by robingroppe** [comment]
True I have fixed it but it wont fix the issue. I reduced the ping count to 10 now as it seems to work this way. When I set it to 50 pings you can watch it go crazy. Testing it on a local vm now.

**Comment by adolfintel** [comment]
@robingroppe is your server behind a firewall or any kind of anti DDOS protection?

**Comment by robingroppe** [comment]
Nope, seems to be an issue with the apache configuration or something. Maybe virtualisation...
Running fine on a local vm with even 500 pings...

https://rbn.gr/screens/1519406612-5833c06864271542d85a01894bf0865c5edcb95d.png

**Comment by robingroppe** [comment]
@hadanin Are you willing to share the code for your results page? :)

**Comment by robingroppe** [comment]
@adolfintel It was in fact a virtualisation related configuration.
