### ISSUE TITLE
Multiple threads

### ISSUE THREAD

**Issue by andrewhearn** [adolfintel/speedtest#119]
Hi, 

I think the sppedtester is single thread at the moment, in  that only a single download/upload happens , would it be possible to have an option to do multiple concurrent downloads at once (eg 6), and then show the results of the combined speed? 

This would help show possible congestion issues and where end user load balancers are in place.

I have been involved with problems where congestion only shows up on single thread transfers, and so this feature would help diagnose these.

I'd suggest the speedtest perform a single thread test, then a 6 thread test and display both results for comparison.

See https://www.thinkbroadband.com/faq/broadband-speed-test#324 for info about their speed tester performing a single thread test then a 6 thread test.

As others have said, it's a great tool, thank you!

**Comment by adolfintel** [comment]
I'm already using multiple connections, see xhr_dlMultistream and xhr_ulMultistream in doc.md.
If you need a comparison between 1 and multiple streams you can easily do it by running a test with those 2 parameters set to 1, and another test with with the default values.
