### ISSUE TITLE
The ability for the users who test speed to get a link of the speed test result

### ISSUE THREAD

**Issue by somethingnottakenyet** [adolfintel/speedtest#121]
Some users may have problem in a certain period, and they need to show the ISP that they have tested their speed in specific date and time and they had issues, so having the ability to give the user a link that shows the result of a speed test which contains the ip address of the testing user  and the date and time of the test could be a great feature.
Thanks in advance

**Comment by adolfintel** [comment]
This was already requested a couple of times, it's on my to-do list for this project, but I don't have an ETA for you yet.

**Comment by somethingnottakenyet** [comment]
Oh ok, so if added this thing i will share it with you so you can use the added code if it was proper enough

**Comment by adolfintel** [comment]
Yea that would be great, you can return an ID from the telemetry or something
