### ISSUE TITLE
HTTP_CLIENT_IP不安全，我认为可以轻易伪造他

### ISSUE THREAD

**Issue by 1265578519** [adolfintel/speedtest#122]
HTTP_CLIENT_IP不安全，我认为可以轻易伪造他

**Comment by adolfintel** [comment]
In english please?

**Comment by ZBrettonYe** [comment]
he said "HTTP_CLIENT_IP is not safe, I think it is very easy to fake one"

**Comment by 1265578519** [comment]
@ZBrettonYe  In fact this is not a problem, but may cause a mysql dos log?
Of course I did not use log.

**Comment by adolfintel** [comment]
Yes you can spam a lot of forged requests to the telemetry if that's what you mean. If you want to implement some sort of ddos protection, feel free to contribute.
