### ISSUE TITLE
garbage.php?r=0.14562423652890177&ckSize=200

### ISSUE THREAD

**Issue by 1265578519** [adolfintel/speedtest#123]
If you visit the URL directly, he will download the 200MB document, without judgment?

**Comment by adolfintel** [comment]
It's limited to 100mb, and it's garbage data, nothing sensitive. What's the problem?

**Comment by 1265578519** [comment]
I just found that modify the ckSize = parameter, the output file size is not 20M, I set the 200M found more than 20M, I did not download to complete him, should be as you said there are 100M limits.
I did see him in the source code.
$data=openssl_random_pseudo_bytes(1048576);

**Comment by yylzcom** [comment]
I found the same problem here. If someone request this url:
garbage.php?r=0.14562423652890177&ckSize=2000

It will download up to 2000M or until the php timeout.

In garbage.php, below the code 

`$data=openssl_random_pseudo_bytes(1048576);
`
add this lines:

```
// Limite the size to 20MB
if($_GET['ckSize']>20){$_GET['ckSize']=20;}
```

Change 20 to whatever you like.
