### ISSUE TITLE
Problem when "GET parameter" is used in configuration for telemetry URL

### ISSUE THREAD

**Issue by lgblgblgb** [adolfintel/speedtest#126]
It seems, for getIP, javascript code uses the url_sep() function, so it works perfectly if I want to configure to use an URL for GetIp like `http://something/some?somevar=1` (with sensing if ? was already used, and using '&' instead of '?'). However it seems it's not the case with telemetry. I got URLs like this for XHR:

    http://somehost/?object=stat?r=0.7440947156259677

while I expect this to be produced:

    http://somehost/?object=stat&r=0.7440947156259677

my corresponding configration for telemetry:

    url_telemetry: 'http://somehost/?object=stat'

I guess, the solution is not hard, only the url_sep() function should be used at the xhr where the post event happens for telemetry. I'm not sure if there is any other problematic case like this, but maybe it's worth to check other cases well. Surely, maybe not so much a "popular" error with a strange config I want to use. Thanks a lot in advance! I've already worked around this issue, but I guess it would be better to solve the problem at project level.

**Comment by lgblgblgb** [comment]
Oh, and surely, I wouldn't embed garbage.php and such into another project like what I want to do with telemetry (that's the reason of my strange need for that telemetry URL) since the performance is very important there. But surely, the final stat ("telemetry") is something which is not performance critical, and some may would like to receive that within a bit more complex situation like only the example telemetry.php in the repository. Hopefully I could explain of my strange need here :-O Thanks.

**Comment by adolfintel** [comment]
You are right, expect a fix in the next hour or so

**Comment by adolfintel** [comment]
It should be fixed now, in master and docker branches.
