### ISSUE TITLE
CLI comman

### ISSUE THREAD

**Issue by pvouzis** [adolfintel/speedtest#128]
Is there a way to run this on the CLI and parse the output? 

 I would use this if I wanted to script this and run the test periodically.

Thanks,
Panos

**Comment by adolfintel** [comment]
No, this is designed to run in a browser.
iperf might be what you're looking for

**Comment by pvouzis** [comment]
Thanks for the prompt response. I am aware of iperf, but I like your test because it would be easier to set up an on-premise server and have unskilled users use that server for bandwidth testing (instead of public servers that are unreliable and give less accurate measurements).

CLI support would be a great feature to add :)

**Comment by mqu** [comment]
I am also interested in such feature.
