### ISSUE TITLE
Installation steps for Debian/Ubuntu

### ISSUE THREAD

**Issue by karibuTW** [adolfintel/speedtest#129]
Hello,
I wrote an article on Speedtest with a tutorial on how to install it on Debian/Ubuntu for a basic usage.
[How to install Speedtest on Debian/Ubuntu](https://freedif.org/how-to-install-selfhosted-speedtest)
Hope it can helps others.

Feel free to help me to improve it ;)

Great project, thanks a lot for sharing it!

**Comment by adolfintel** [comment]
Thanks. I've added it to the README
