### ISSUE TITLE
Crashes and issues with very fast connections

### ISSUE THREAD

**Issue by alexatkinuk** [adolfintel/speedtest#13]
Tried your test server using Firefox 50.1.0 on Fedora 25 and it reaches around 8.5Mbit then freezes the browser maxing out the CPU.  After a while Firefox reports the tab has crashed and the PC is responsive again.

**Comment by adolfintel** [comment]
It works fine here. If firefox is freezing there may be another reason. The speed test runs in a separate thread, there is no way it could lock up the entire tab like that.

![2017-01-21 20_30_50-dosse s x desktop minnowboard_1](https://cloud.githubusercontent.com/assets/16307689/22177143/bfeb4074-e018-11e6-8ea5-d0bb5f482b5c.png)

**Comment by alexatkinuk** [comment]
I have installed a copy on my local server and done further testing over 
Gigabit ethernet and 802.11ac WiFi with my laptop.

On Chrome the test fails to complete on all but example4, giving a 
"chrome killed by SIGILL" message in the system error log.  My guess 
would be the graphs taking up some of the CPU load is throttling it, 
avoiding the crash.  This would concur with the fact it doesn't reach 
the same test speeds as the other tests. Example1 sometimes hits 950Mbit 
before crashing, other times it doesn't report anything at all.

As for Firefox, it seems to max one core and then slowly exhausts the 
RAM.  It is kswapd that ultimately causes the machine to stop responding 
and the browser crashes when the system runs out of RAM to allocate.

I tried switching to my laptop (Pentium 3805U) as it has a fresh install 
of Fedora 25 whereas my desktop is several years of upgrades.  Test 
initially done over 802.11ac:
On Firefox its heavily throttled by the CPU, it only hits 30Mbit whereas 
iperf can do 300-400Mbit.  I get the same download result on ethernet 
except now upload manages to hit 600Mbit.
In Windows 10, the results were more or less the same, if not slightly 
lower performance.

Chrome manages to hit 400Mbit down, the upload result however is all 
over the place with an end result of 66Mbit.  Once plugged into Ethernet 
it maxed out the CPU then crashed.
Chrome on Windows 10 however does not crash, but its showing wildly 
different results between tests.  First came out at 188Mbit down, 
285Mbit up.  Second at 229Mbit down, 158Mbit up.  So it seems to be 
throttling somewhere whereas Linux ran unbounded and thus the crash.

While on my laptop I tried your hosted version of the test too.
Firefox was clearly CPU bound as the starfield dropped to a very low 
frame rate with an end result of 24.99Mbit down, 10.6Mbit up. Chrome 
managed 23.82MBit down, 16.44Mbit up.
I then ran the speedtest from my VPS and got very similar results.

For reference I then ran a test from dslreports.com/speedtest which gave 
me 75.3Mbit down, 16.1Mbit up.

Alex.

**Comment by adolfintel** [comment]
I think I know the reason why this is happening. You're using a reaaaaally fast connection, and when the download test loads garbage.php (which generate an endless stream of random data), it receives so much data in those 10-15 seconds that it maxes out the CPU and fills up the RAM.
I didn't think of it when I made the test...
A possible workaround for the moment could be this: delete garbage.php and replace it with the garbage.dat linked in the readme (100mb), and edit example4.html to replace garbage.php with garbage.dat.
Now every time it downloads 100mb it will purge it.
It may still max out the CPU at that speed though, but not the RAM.

**Comment by adolfintel** [comment]
Yea, I tried.
The one on my site stores all results, and most of the time I see they are accurate, but about 5% of the tests show unusual results, like a download of 0.8 Mbit and an upload of 600 Mbit. Clearly they are wrong but I have no idea how to improve it. The way it works is so simple, how can it be wrong?

**Comment by dennore** [comment]
very nice and small code, but on my safari on ios crashes on fast connections > 100Mbit too.
is there any way to add a multistream upload/download into a single html page? to max out even > 1Gbit connections?

i cant get more than 600Mbit on Chrome, within a single instance.
if i run multiple chrome sessions at the same time ill get the 1Gbit working...

**Comment by adolfintel** [comment]
If I use more connection it will crash even harder

**Comment by dennore** [comment]
on Chome (MAC and PC) its not crashing for me at all... it just cannot max out the line within a single session... but thats pretty common because a single TCP Session max troughput depends on the packetsize and Ping: a calculator is here https://www.switch.ch/network/tools/tcp_throughput/
