### ISSUE TITLE
Is there any document describe how to use speed test node version?  

### ISSUE THREAD

**Issue by sawyerbutton** [adolfintel/speedtest#136]
I know the node version just released but is it possible to write an easy tutorial for that?

**Comment by dunklesToast** [comment]
Hi!
For more information about the NodeJS Version, check out the [repo's wiki](https://github.com/adolfintel/speedtest/wiki)!
There you should find most information. If there are still unanswered questions, just ask me here!


tom

**Comment by sawyerbutton** [comment]
@dunklesToast Hi, Tom. Very glad to see your response. 
I have several questions now. 
First one is can I deploy the node server on my laptop just for testing? 
The second one is I followed every step mentioned in the 'Installation (Node.js)'. Everything is good except 'Start the Speedtest Server: node Speedtest.js'. Node throws an error 'Cannot find module '/Users/admin/WebstormProjects/SpeedTest_NodeServer/speedtest/Speedtest.js'. I think the error is because node does not find the speedtest.js file in the main dir. 
Should I run the SpeedTest.js file under src dir?
My package.json looks like this. And my node version is 8.9.4
<img width="567" alt="screen shot 2018-05-03 at 2 31 00 am" src="https://user-images.githubusercontent.com/14297658/39562512-0a4c1c9e-4e7a-11e8-915f-c821b23a533a.png">

**Comment by sawyerbutton** [comment]
Alright, I run the server by running it in the src dir.

**Comment by sawyerbutton** [comment]
Currently, everything works fine. But it looks like that the ISP service has not deployed on the HTML example. Good Job and Look forwarding.

**Comment by dunklesToast** [comment]
If you are running it on you local laptop, the ISP Service does not work, since it’s your local domain.

**Comment by sawyerbutton** [comment]
@dunklesToast  Thanks, I will try more like deploying the server on the Heroku and see what will happen.
