### ISSUE TITLE
Incorrect upload with Chrome 67 - Firefox 61 works fine

### ISSUE THREAD

**Issue by danodemano** [adolfintel/speedtest#139]
Hello and let me say I LOVE this speedtest web app.  So slick and easy to use/customize.

I have a strange problem though, I thought it was firewall related but Firefox works as expected so I don't believe that to be the case.  Chrome on the same network gives < 1Mbps when testing when it should be 10+.  I've even tried incognito to rule out extensions.  

Chrome results:

![2018-06-27 23_15_09-consolidated cooperative speedtest](https://user-images.githubusercontent.com/1128744/42011297-d26be18e-7a60-11e8-9a80-8dce675f7a0c.png)

It also hangs for a VERY long time while testing and the progress bar goes past the end:

![2018-06-27 23_17_00-consolidated cooperative speedtest](https://user-images.githubusercontent.com/1128744/42011314-e62880a6-7a60-11e8-9f68-10438b315d3a.png)

Network tab for Chrome:

![2018-06-27 23_14_13-](https://user-images.githubusercontent.com/1128744/42011326-f5cc10cc-7a60-11e8-8a4d-a8d8166e40a7.png)

In Firefox 61 it works as expected:

![2018-06-27 23_15_55-consolidated cooperative speedtest](https://user-images.githubusercontent.com/1128744/42011339-01dd63de-7a61-11e8-90a3-9fa570d1dc34.png)

Network tab for Firefox:

![2018-06-27 23_19_54-consolidated cooperative speedtest](https://user-images.githubusercontent.com/1128744/42011348-0cc1346a-7a61-11e8-9e28-275cd7962bcf.png)

Client is an i7 with 16GB of RAM and an SSD.  1Gbps Ethernet link to the firewall.  Windows 10 Enterprise x64.

Server is a dual 6-core Xeon something with 16GB of RAM, a 10Gbps NIC, and SSD.  It's running CentOS 7 and Apache.  PHP 7.2 I think but can confirm tomorrow.

Any thoughts/suggestions/fixes appreciated!

**Comment by adolfintel** [comment]
I'm unable to reproduce the problem on chromium 66, 67, 68 (besides, chromium is my main test target for the speedtest, I would have noticed the problem).
My guess is that your firewall is blocking, delaying or throttling some of the requests made by the client. It only affects chromium because multistream is enabled by default, making multiple connections instead of just 1 like firefox.
Try adding xhr_ulMultistream:1 to the speedtest settings and see if I'm right.

**Comment by adolfintel** [comment]
Also, I assume you're on the latest version of the speedtest (4.5.5 or master)
