### ISSUE TITLE
Feature Request: Share feature

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [adolfintel/speedtest#142]
It would be nice to temporarily store images of the speed test results (or similar) and allow users to share the path to the image rather than have to take a screenshot.

**Comment by dunklesToast** [comment]
Hmmm. At first I would create page where you can view the telemetry results.
Something like: https://youspeedtest.host/result/<ID>
If this feature works, we could implement image generation.

**Comment by adolfintel** [comment]
I've been planning on doing this for a while but I've always been busy with other stuff.
We could return an ID with the telemetry and then add a page like result.php?id=##

**Comment by adolfintel** [comment]
Image generation could also be an option but I don't want to store thousands of useless images on the server so it has to be done when the request comes in

**Comment by adolfintel** [comment]
Implemented in 4.6

**Comment by adolfintel** [comment]
![image](https://user-images.githubusercontent.com/16307689/43729380-6b9433c8-99a8-11e8-9b6b-cff2f43d93a3.png)

**Comment by jodyborn3** [comment]
Hello, I want to know if there is a way to change the share URL to http://hostname/speed/results/?ip="ip address here" with a history at least 5  past speed results?

**Comment by adolfintel** [comment]
@monacheprojects it can be done but I don't have time to do it right now, maybe in a future version

**Comment by monacheprojects** [comment]
> @monacheprojects it can be done but I don't have time to do it right now, maybe in a future version

Have you looked into this yet?

**Comment by adolfintel** [comment]
@monacheprojects Unfortunately no, I have added other features and improvements first
