### ISSUE TITLE
Feature Request: Add country to database

### ISSUE THREAD

**Issue by rjsorto** [adolfintel/speedtest#143]
You should add the country code / country to the database, it will be easiest to show a table of latest tests displaying the ip or country code or country name or country flag or all of them without causing more requests from the site to the ip data providers

**Comment by adolfintel** [comment]
Yes, I will add an ispinfo field to the database, it will take a few hours to do it and test it.

**Comment by adolfintel** [comment]
And it's done.
I've actually just stored the whole output from getIP into the database, which contains the IP address (detected using a better method compared to telemetry.php), ISP info, country and distance.
The new ispinfo field should look like this: 95.244.93.82 - AS3269 Telecom Italia S.p.a., IT (410 km).
If ISP info detection is disabled, it will display only the IP, or nothing at all if IP detection is also disabled.

**Comment by rjsorto** [comment]
Perfect, thanks!

**Comment by rjsorto** [comment]
Have you check the values in the database? I was using the updated scripts and getIP.php is still returning a formed string instead of the ipinfo.io object's (and extra data) to the worker, so sendTelemetry is posting the string to telemetry.php.

I don't know if it's only me, but I modified again getIP.php and the getIp worker and got it to work (in the hurry to test the updates didn't backup my modified scripts ).

**Comment by adolfintel** [comment]
Yes, that's what I did. The string is easy to parse, it's just IP - ISP,Contry (distance).
To return the ipinfo object would require some extra work. Right now I'm working on #142, so maybe I'll do it after that
