### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by History73** [adolfintel/speedtest#145]
Hi, your project is perfect!! Thank you!!
It is possible to integration a counter in the front with a number of tests made in real time?

Sry for my bad English :)

**Comment by History73** [comment]
To put a simple counter you can do the following ..
Download the file totatests.php from here:

[totaltests.zip](https://github.com/adolfintel/speedtest/files/2716512/totaltests.zip)

Put the file in your root.
You can call the file from http://yoursite1.com/totaltests.php
If you can not see it changed the code:
`echo "<font color='white'>Total Tests: </font>". "<font color='white'>". $row["id"]."</font>";`
with this:
`echo "<font color='black'>Total Tests: </font>". "<font color='black'>". $row["id"]."</font>";`

The meter is automatically refreshed every 5 seconds.

Now if you want to display the counter on your Index.html page you can easily do it with iframe:
`<iframe src="http://www.yoursite1.com/totaltests.php" width="50%" height="40" frameBorder="0"></iframe>`
Put the iframe code where you want in your page.

Thats it!

Again thanks for your great project..

**Comment by adolfintel** [comment]
That's a very 90s way of doing it. It works, but this is something that's better done with XHR instead of embedding a page (lighter, no lag spikes during the test).
If you're going to use it, at least use CSS instead of those horrible font tags and iframe attributes.

**Comment by History73** [comment]
You are right. 
I am not a programmer. 
I just found a simple solution and wanted to share it :)
