### ISSUE TITLE
Unable to get IP address and download test seems slow

### ISSUE THREAD

**Issue by davboroyal** [adolfintel/speedtest#147]
I get this from the getip.php page:
Parse error: parse error, expecting `')'' in E:\web\htdocs\supportweb\speedtest-master\getIP.php on line 22

And download seems really slow ... less than a Meg versus 93 Meg Upload from my testing which I would expect ...

I'm running the code on an older windows 2008 box with Apache/PHP
Apache/2.2.11 (Win32) mod_ssl/2.2.11 OpenSSL/0.9.8i PHP/5.2.9-1

Any places to start .. you mentioned a garbage.dat file, I downloaded, but not quite sure how to reference, etc ..
![image](https://user-images.githubusercontent.com/42212038/43843107-2b5e0af8-9afd-11e8-99d3-300361e08983.png)

**Comment by davboroyal** [comment]
Sadly it's an internal server.  Can't get access to you ...

**Comment by adolfintel** [comment]
Ok, I'll try to help you anyway.
Try to connect to http://yourserver/garbage.php, does it start a download? If it does, is it a large file or just a few bytes?

**Comment by davboroyal** [comment]
It downloaded a 1K file

**Comment by davboroyal** [comment]
random.dat

**Comment by adolfintel** [comment]
Open it in notepad, there's probably a server error inside

**Comment by davboroyal** [comment]
<br />
<b>Fatal error</b>:  Call to undefined function openssl_random_pseudo_bytes() in <b>E:\web\htdocs\supportweb\speedtest-master\garbage.php</b> on line <b>18</b><br />

**Comment by adolfintel** [comment]
Looks like the OpenSSL module isn't configured correctly in PHP

**Comment by davboroyal** [comment]
Ughh ... seems to be, but not sure what to check ... it's in the php.ini and enabled.

**Comment by adolfintel** [comment]
Try reinstalling the module, maybe it will fix it

**Comment by davboroyal** [comment]
Would this affect the GETIP.php as well ?

**Comment by adolfintel** [comment]
getIP doesn't use OpenSSL, there must be another problem with that. Line 22 doesn't contain any syntax error, unless you modified it.

**Comment by davboroyal** [comment]
Well it's there and working, perhaps an older version .. is there a way to not use the openssl ... and just use the file download for speedtest ?

**Comment by adolfintel** [comment]
Yes, you can use a large file instead of garbage.php, it's explained in the documentation. See the url_dl parameter

On August 8, 2018 7:10:12 PM GMT+02:00, davboroyal <notifications@github.com> wrote:
>Well it's there and working, perhaps an older version .. is there a way
>to not use the openssl ... and just use the file download for speedtest
>?
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/147#issuecomment-411481515

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davboroyal** [comment]
Nope, didn't modify the line ... I was also looking at the url_dl parameter and where do I edit to put the location of the file as opposed to the garbage.php ?

**Comment by adolfintel** [comment]
In your HTML file look for the line that says w.postMessage('start') and replace 'start' with 'start  {"url_dl":"garbage.dat"}'.
More about this here: https://github.com/adolfintel/speedtest/wiki/Changing-the-test-settings

**Comment by davboroyal** [comment]
Found it just before you posted .. edited and it worked.. thanks ..
Now just need to get the getip.php working .. not sure why .. looks fine where it's complaining.

**Comment by adolfintel** [comment]
Maybe the PHP version is too old? The oldest one I tried was 5.3

On August 8, 2018 7:31:44 PM GMT+02:00, davboroyal <notifications@github.com> wrote:
>Found it just before you posted .. edited and it worked.. thanks ..
>Now just need to get the getip.php working .. not sure why .. looks
>fine where it's complaining.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/147#issuecomment-411488329

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adolfintel** [comment]
Yes, I just checked again and 5.4 seems to be the oldest version that can run getIP. 5.3 gives me a syntax error.

**Comment by davboroyal** [comment]
Ok, I’ll find another option for that ...  Thanks for your help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dtech4you** [comment]
so i am having somewhat same problem but not sure why. so i have 2 servers i am testing on both linux both running same setups the only diffrence being that one is local without a domain and the other is external with a domain. the web-server running it is ngnix not apache2. so the problem is the local server works like one would hope, but the external server is having problems talking to the php files which i am not sure why and or how my only guess is has something to do with the letsecrypt domain name sky.quickbox.io/speedtest  

https://vgy.me/RFjRlk.png

any help in getting this working would more than likely result in donations down the road.

**Comment by adolfintel** [comment]
@dtech4you It looks like a problem with the web server configuration. I'm not quite what exactly because I never used nginx

**Comment by dtech4you** [comment]
figured out the problem but not the solution and not sure if it has to do with how nginx is but it is broke due to the domain name not sure if its not understanding the uri or what wondering how might go about this as tried with same setup on a external server without letsencrypt and works just fine
