### ISSUE TITLE
Bad results with high speed connections

### ISSUE THREAD

**Issue by alevesely** [adolfintel/speedtest#15]
This seems to be similar to issue #13, but I experienced no crashes, so I open a new issue.

I'm testing with Chromium 56.0.2924.76 Built on 8.7, running on Debian 8.7 and Mozilla Firefox 45.7.0. The server is connected via gigaethernet.  On FF, download speed initially reaches high values, but slows down at about ~50MB and ends showing a speed of a few MBs.  It may depend on the number of open tabs I have.  On Chromium, it shows a few hundres Mb/s.

I tried to stop the test before memory is hogged, see [speedtest_worker.patch.txt](https://github.com/adolfintel/speedtest/files/787339/speedtest_worker.patch.txt).  That way I get 161.74 Mbit/s on FF, 260.10 Mbit/s on Ch.  Upload is, respectively, 549.38 Mbit/s and 266.96 Mbit/s, so measured values are about 1/2, 1/4, and 1/8 of nominal speed; I don't think they could get much better than that...

**Comment by adolfintel** [comment]
Yes, this is the same as issue #13, it just doesn't crash on your machine.
