### ISSUE TITLE
Why does not the download rate correct?

### ISSUE THREAD

**Issue by behzad27** [adolfintel/speedtest#150]
hi my friend,i download your file and install that on my server on the xampp control panel,but when i try show the end user internet download speed,dont show correct but in this link:
http://speedtest.fdossena.com/
show the internet speed correct,i think that the reason your server in italy and my server in my country?that correct?thanks.

**Comment by dunklesToast** [comment]
Hey!
Could you please provide more info?
Where is the Server located?
Whats your internet speed?
How do you installed the Speedtest?

It doesn't (really) matter where the server is located. Well, if its near you, the result could be more accurate.

**Comment by adolfintel** [comment]
No, you probably configured something wrong.
Write me at info@fdossena.com and I'll help you troubleshoot it.

**Comment by behzad27** [comment]
-my server locate in iran-tehran.
-my internet speed 16Mbps but speed test show me 9 Mbps
-download the all file from github and copy all file in xampp web server.
