### ISSUE TITLE
FR: Documentation: Sqlite

### ISSUE THREAD

**Issue by gerroon** [adolfintel/speedtest#153]
Hi 

Can you please add detailed instructions for the Sqlite3? Not everyone understands the database backends and the wiki page barely mentions the Sqlite part, does not tell where and how to create the necessary database.

thanks

**Comment by adolfintel** [comment]
Sqlite requires almost 0 configuration. All you have to do is edit telemetry_settings.php to tell it where you want to save the database. The database is created automatically the first time the telemetry is used.
Is there something specific you wanted to know?

**Comment by gerroon** [comment]
@adolfintel 

thanks for the reply. It was not clear to me how the sqlite is handled. Maybe you can add that line to the doc?
