### ISSUE TITLE
mcrypt has been removed from php 7.2

### ISSUE THREAD

**Issue by choicky** [adolfintel/speedtest#154]
ubuntu 18.04 installs php 7.2 by default.
Hhowever, mcrypt has been removed. 

how to update the source to adapt php 7.2?

**Comment by adolfintel** [comment]
I'm not using mcrypt, what problem are you having?

**Comment by choicky** [comment]
The `Ubuntu (External)` under `Quick installation videos` section of [speedtest](https://github.com/adolfintel/speedtest) tell us install basic requirements as follows:

``` bash
apt install libapache2-mod-php php-mcrypt
```

I thought `php-mcrypt` is required.

**Comment by adolfintel** [comment]
I didn't make that guide, I sent him an email to warn him about this problem.
Anyway, mcrypt is not required, but OpenSSL is (Ubuntu probably already installs this with PHP)
