### ISSUE TITLE
Speedtest not working with internal IPs

### ISSUE THREAD

**Issue by meifi** [adolfintel/speedtest#155]
Hi, 

very nice Project. Thank you! 

Since i've downloaded the new Version today, i'm not able to make speedtest 
with internal ips. in Version from 29.06 it works without any issues. 

I think it could'n check that is an internal ip, because it is Nothing shown. in the
old Version it shown isp unknown

**Comment by adolfintel** [comment]
It works fine on my machine. are you sure you don't have a firewall or something blocking you?

**Comment by adolfintel** [comment]
Oh, I think I found the problem, maybe PHP is throwing a warning and the script can't parse its output.
Try updating getIP.php from the current master version and let me know.

**Comment by meifi** [comment]
Yes, it's working now. Thank you very much! Perfect.
