### ISSUE TITLE
Telemetry for different links on same instance

### ISSUE THREAD

**Issue by adopilot** [adolfintel/speedtest#157]
First at all , thanks on great work.

My scenario is following:
I have server behind router.
My router has multiple wan connection.
My router has nat(ed) all wans to server hosting speed test and it is working nice.
I am able to test all of my wan connection sauces.

What I want to do is to save telemetry for tests.
I set  telemetry and it is working fine.
But problem is I can't figure in db for tests over which connection test was made.
Is there chance to we get in speedtest_users table requested url or ip from client which is called.
It will bi cool if we have in one db and table speed tests from all nics (links,wnas )which can be filtered speared by one by one

.

**Comment by adolfintel** [comment]
I'm not sure if I understand your request, but I think you can do it by modifying telemetry.php, all you have to do is store which link the connection came from in the extras field of the DB. How you do this depends on your specific scenario, there's probably a server variable in PHP that tells you which link was used, or an HTTP header.
