### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Cougar73** [adolfintel/speedtest#159]
Hello,

first of all I need to say that you are doing a terrific job with this speedtest webserver setup.
It helped me already a lot with speed related issues on the network where i work.

One thing that would be handy, as seen from a network troubleshooting perspective, is to also display the return path routing of the traffic.

Since we use different network lines it is usefull to also know over which network path the Speedtest traffic flows.  So having a traceroute like output option would be great 

I added some mockup based on ubuntu output #mtr <Client IP> -x file.xml
![mockup1](https://user-images.githubusercontent.com/43401099/45738356-7a1bfd80-bbf0-11e8-8952-a2e14e582eba.jpg)

could this be easily implemented ?

greetz
Phil

**Comment by adolfintel** [comment]
As cool as it would be, you can't do a traceroute over HTTP.

**Comment by bernd-wechner** [comment]
Interesting, but the server running speedtest can run a traceroute not? PHP should be able to handle that fine I'd have thought?

**Comment by Cougar73** [comment]
> Interesting, but the server running speedtest can run a traceroute not? PHP should be able to handle that fine I'd have thought?

Afaik, there are indeed php traceroute modules. but not sure how i would implement it here ?
