### ISSUE TITLE
Results slightly high

### ISSUE THREAD

**Issue by decryptedchaos** [adolfintel/speedtest#16]
This issue is very close to #12 

However,  my experience is that the results are too high as shown below 

This is the baseline test,  from the same datacenter,   Notice about a 1-2MBIT difference in the download and about 30ms difference in the ping which is relevant because the servers are in the same datacenter.

![Baseline](http://www.speedtest.net/result/6082822687.png)

If my connection was capable of 8MBIT i wouldn't question it,  but I've never been able to get 8MBIT from this particular connection,  so something seems off to me. 

Sometimes the speed test will show even higher results 8.5-9MBIT
![speedtest](https://cloud.githubusercontent.com/assets/1302391/23332288/b5b9aad4-fb3c-11e6-9fea-e7af2db0b21f.png)

**Comment by adolfintel** [comment]
There's only so much I can do. I'll leave the issue open, maybe someone more skilled than me can improve it.

**Comment by decryptedchaos** [comment]
Your good man,   Wasn't really putting it up here as a demand for a fix,  rather feedback for you and the community in hopes that someone can work towards a fix. 

I myself am going to be messing with the code to see if I can solve it,  I think the problem is in the math or timing.

**Comment by jdc20181** [comment]
None are 100% accurate it could be such a thing its reverse and this project is more accurate. There really is no real way to tell. Unless you know what your speed should be and you are using a hardwire connection (not wifi)
