### ISSUE TITLE
Feature request: test ping under load

### ISSUE THREAD

**Issue by koenkooi** [adolfintel/speedtest#162]
## Description
Currently ping is tested seperately from upload/download, it would be useful to have an option to measure it *during* the upload and download tests.

## Why it should be implemented
Testing ping under load and comparing them to the idle situation is a measure of how bad the bufferbloat on a connection is. 30ms idle ping can easily become a full second during upload tests.

**Comment by adolfintel** [comment]
Combined testing is already planned for the next update as you can see under projects. It will be implemented as soon as I have the time
