### ISSUE TITLE
Nothing shows after I clicked 'start' bottom

### ISSUE THREAD

**Issue by zppznn** [adolfintel/speedtest#164]
Hi Adolfintel,

It is really appreciated to use and test your work on my server. After configuring speedtest on my Ubuntu 16 server on my vps, and paste the index.html to /var/www/html, I can access the website on my chrome browser. The issue is I can see the gauges and start button, but after I clink the button, nothing changes.

I follow every step on this site: https://freedif.org/how-to-install-selfhosted-speedtest 
and I install LAMP(mysql server ) as well, even though I dont know how you use mysql database in your speedtest service because I set the password to 12345 myself during the mysql configuration. 

I can access and see results when using your link for the speedtest. I dont know am I missing something. Please advise.
Thank you!

**Comment by adolfintel** [comment]
Please don't open issues for troubleshooting. Issues are for bugs, Write me at info@fdossena.com instead.

That being said, if you give me the url of your speedtest I'll check it out for you.

**Comment by zppznn** [comment]
I will write an email instead. I am so sorry!
