### ISSUE TITLE
Hitting PHP memory limit due to longtext fields

### ISSUE THREAD

**Issue by fmkaiser** [adolfintel/speedtest#167]
## Description
At least with PHP 5.4 (RHEL 7), stats.php is hitting the PHP memory limit due to the way mysqli handles the longtext fields: https://bugs.php.net/bug.php?id=51386.

`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4294967296 bytes) in /var/www/html/speedtest/telemetry/stats.php on line 94`

The mentioned workaround of using store_result() before bind_result() works, if you want I can submit a pull request.

**Comment by adolfintel** [comment]
Makes sense, send a PR if you can.
Why is it trying to store a 4gb string though?

On October 17, 2018 11:20:04 AM GMT+02:00, Florian Kaiser <notifications@github.com> wrote:
>## Description
>At least with PHP 5.4 (RHEL 7), stats.php is hitting the PHP memory
>limit due to the way mysqli handles the longtext fields:
>https://bugs.php.net/bug.php?id=51386.
>
>`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted
>(tried to allocate 4294967296 bytes) in
>/var/www/html/speedtest/telemetry/stats.php on line 94`
>
>The mentioned workaround of using store_result() before bind_result()
>works, if you want I can submit a pull request.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/167

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adolfintel** [comment]
Nice implementation 😂

I'll merge your PR as soon as I get home. Thank youb

On October 17, 2018 12:27:31 PM GMT+02:00, Florian Kaiser <notifications@github.com> wrote:
>The "log" column is of type longtext which may be up to 4GB in size.
>
>I'm not that familiar with PHP/MySQL specifics either, but for some
>reason it doesn't know the actual size of the records when bind_result
>is called without store_result, so it allocates buffers of the maximum
>allowed size.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/167#issuecomment-430575884

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
