### ISSUE TITLE
Does not work properly with all browsers.

### ISSUE THREAD

**Issue by ke-mccormick** [adolfintel/speedtest#17]
Does not work on IE 11 runs first test then stops working.
Ping does not work on FireFox 51.0.1.
Chrome and Opera work fine.

I did not try Safari or Edge.

**Comment by adolfintel** [comment]
Hi,
IE11 is not supported, as you can see in the readme, the test requires Edge 12 at least
Chrome, Opera, Edge and Safari work fine
FF51 works on my machine, but I'll look into it, thanks for the report

**Comment by adolfintel** [comment]
Should be fixed with latest version (commit e87c8c861b0f63d3ddc7ead1cb775df2daf930ce)
