### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by debpedrano** [adolfintel/speedtest#170]
hello,

Do you need a project logo? I can make it for you, for free. Just tell me some ideas about how it look like.

thanks

**Comment by adolfintel** [comment]
Hi,
Yea, the project could use a logo if you want to give it a shot.
This is the current "logo", it's just something I made in 5 minutes.
![cover](https://user-images.githubusercontent.com/16307689/47266411-478a5b00-d536-11e8-84ec-a4dc34ba53b6.png)

**Comment by debpedrano** [comment]
How about this one @adolfintel ?

![image](https://user-images.githubusercontent.com/40510200/47268477-2e100000-d584-11e8-9fd2-8cd131ccd56b.png)

**Comment by debpedrano** [comment]
![image](https://user-images.githubusercontent.com/40510200/47268528-d7ef8c80-d584-11e8-8146-53a74ba8bde7.png)

**Comment by adolfintel** [comment]
I like the first one, can you apply some antialiasing on the indicator?

**Comment by debpedrano** [comment]
How about this one? @adolfintel 

![image](https://user-images.githubusercontent.com/40510200/47287685-a7abfa80-d625-11e8-935f-73d1d6f251c4.png)

**Comment by adolfintel** [comment]
I like it, try removing the meter in the background and inverting that blue gradient

**Comment by debpedrano** [comment]
@adolfintel 

![image](https://user-images.githubusercontent.com/40510200/47291901-f9f61700-d637-11e8-9321-c0e611f905d6.png)

**Comment by adolfintel** [comment]
Nice. Send me the PNG (and possibly the project file) and I'll use it.
How do you want to be credited?

**Comment by debpedrano** [comment]
I will create
- Fav icon
- Logo Type
- Logo Mark
- Black and White Version
( png, jpeg, and svg ) I will just send you a Pull Request

**Comment by adolfintel** [comment]
Alright, thanks 

On October 22, 2018 3:07:17 PM GMT+02:00, Deb Pedrano <notifications@github.com> wrote:
>I will create
>- Fav icon
>- Logo Type
>- Logo Mark
>- Black and White Version
>( png, jpeg, and svg ) I will just send you a Pull Request
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/170#issuecomment-431830138

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by debpedrano** [comment]
Before i will create the final files, are these okay ?

![image](https://user-images.githubusercontent.com/40510200/47332380-acb68b80-d6b1-11e8-8bfd-ed3b89a5dd11.png)

**Comment by adolfintel** [comment]
Yea, looks good.


On October 23, 2018 4:52:45 AM GMT+02:00, Deb Pedrano <notifications@github.com> wrote:
>Before i will create the final files, are these okay ?
>
>![image](https://user-images.githubusercontent.com/40510200/47332380-acb68b80-d6b1-11e8-8bfd-ed3b89a5dd11.png)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/170#issuecomment-432069225

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by debpedrano** [comment]
I already sent a Pull Request @adolfintel  , thank you.

**Comment by debpedrano** [comment]
@adolfintel  what if I will just send you the google drive link to access all the files, and I will just PR those png and jpeg files.
