### ISSUE TITLE
Blank IP address 

### ISSUE THREAD

**Issue by ddericco** [adolfintel/speedtest#178]
## Description
IP addresses are not displayed when running a speed test. All other information appears to be accurate based on existing, but the address itself is just blank. `getIP.php` completes with a status code `200`, and I can successfully `curl ipinfo.io` from the server,  but the information isn't displaying for whatever reason.

## Server
CentOS Linux release 7.5.1804 (Core)
Apache/2.4.6 (CentOS)
PHP 7.0.32 (cli)

**URL**: https://speedtest2.gcet.net

Using the `example-gauges` template.

## Client
Tested on Chrome & Firefox on Ubuntu 18.04, and Edge & Chrome on Windows 10

## Steps to reproduce
* Run speedtest
* `IP Address:` field remains blank

## Expected behaviour
IP address would be displayed

## Screenshots
Blank IP address:
![image](https://user-images.githubusercontent.com/30156588/47863320-635eee00-ddcd-11e8-9800-3b94c3b55ccc.png)

Network screenshot from Firefox running on Ubuntu 18.04 client:
![image](https://user-images.githubusercontent.com/30156588/47863380-84274380-ddcd-11e8-91b2-1ba6ce627110.png)

**Comment by adolfintel** [comment]
Not a bug, it looks like it times out.
Can you make sure that your server is allowed to connect to ipinfo.io?

**Comment by ddericco** [comment]
Thanks for the quick reply! Pings to ipinfo.io from the server respond normally, and running a `curl` on `ipinfo.io` shows no errors:

```
{
  "ip": "172.103.76.60",
  "city": "Greenfield",
  "region": "Massachusetts",
  "country": "US",
  "loc": "42.5899,-72.5982",
  "postal": "01301",
  "phone": "413",
  "org": "AS395922 GCET"
```
Are there additional steps I can take to try and narrow this down?

(Also, if this is not the appropriate place to follow up, please feel free to direct me elsewhere!)

**Comment by adolfintel** [comment]
Yea, usually I do troubleshooting via email so that people watching the project don't get notified about stuff that's not relevant to them, but we're already here so...

Are you sure that PHP is allowed to connect? Or that proxy settings are correct? Anything suspicious in the server log?

**Comment by ddericco** [comment]
For historical purposes - issue was resolved by installing the `php70u-json` package. See [this page](https://github.com/adolfintel/speedtest/wiki/Installation-(CentOS-7-with-PHP7)) in the wiki.
