### ISSUE TITLE
Problem integrating with jquery

### ISSUE THREAD

**Issue by muhammadarsalansiddiqui** [adolfintel/speedtest#179]

**Comment by adolfintel** [comment]
You need to tell me something about your problem if you want me to help you.

**Comment by muhammadarsalansiddiqui** [comment]
Okay
I'm using Xampp on windows 10 x64, i'm integrating your multi server test on my media portal website which i'm developing, the problem is when i put all you script and html it won't work it stuck on selecting a server and never loads the test page. then i try to look around by removing double checking the scripts and found that it is conflicting or having problems working alongside jquery. i remove jquery and the selecting a server message gone and shows the speedtest form and it is working propely.
I'm using bootstrap 3.3.7 css and js and jquery 1.12.4 although i try all jquery version none of them is working with it.

I have news ticker and image lazy load and menu and some other which is dependent on jquery.

**Comment by muhammadarsalansiddiqui** [comment]
![h65g4h165fg4h65](https://user-images.githubusercontent.com/36761603/47952508-5b9c7680-df92-11e8-9843-5075fa748848.png)

this is my site implementing your multi server speedtest. have remove my code which rely on jquery and the speedtest for is shown but this page looks different from my theme.

![jericho notifications](https://user-images.githubusercontent.com/36761603/47952596-dd40d400-df93-11e8-9228-b12e401cc556.png)

and this is the result when i add jquery, i'm adding jquery in bottom of the page

**Comment by adolfintel** [comment]
Can you tell me what's conflicting with jquery? Do I have a function with the same name or something?

**Comment by muhammadarsalansiddiqui** [comment]
did you get , what my problem is ?

**Comment by adolfintel** [comment]
I'm trying to reproduce your problem but I can't.
I've added this to my page and it works just fine ```<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>```

**Comment by muhammadarsalansiddiqui** [comment]
you've tried mpot or master ? so you want to say that web worker is not conflicting with jquery ?

**Comment by adolfintel** [comment]
I tried with mpot, here's the link: http://speedtest.fdossena.com/mpotdemo/index-jquery.html

**Comment by muhammadarsalansiddiqui** [comment]
alright, thanks for your help.
