### ISSUE TITLE
Option for choosing between MBps, and mbps.

### ISSUE THREAD

**Issue by whiskeyalpharomeo** [adolfintel/speedtest#184]
Please add an option for choosing the unit of measurement - Megabytes/s, or Megabits/s.

Most people subscribe to a certain tier of service which is described, by their providers, in megabits per second.

Ideally, this would simply be a drop-down on the test page, and the user could choose the unit of measure.  Alternatively, you could simply allow the unit of measure to be specified in a config file, based on the administrator's preference.

**Comment by adolfintel** [comment]
Yea, it's a good idea. I'll add better formatting options in the next release
