### ISSUE TITLE
Upload issue with backed server windows 2016

### ISSUE THREAD

**Issue by History73** [adolfintel/speedtest#185]
I have Upload issue with backed server windows 2016.
The error on the speed test page (f12 button) is:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://myserver.net/empty.php?r=0.40898862427227745. (Reason: CORS request did not succeed).

Do you know anything about this issue?

Thanks,

**Comment by adolfintel** [comment]
Please write me at info@fdossena.com for troubleshooting

**Comment by History73** [comment]
For anyone who has the same issue.
Windows Server 2016
For Web Servers with IIS 10.
To solve the problem, make a file named web.confing  and paste this code:

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <cors enabled="true" failUnlistedOrigins="true">
            <add origin="*" />
            <add origin="http://*.yoursitespeed.com" <--you site
                 allowCredentials="true"
                 maxAge="120"> 
                <allowHeaders allowAllRequestedHeaders="true">
                    <add header="header1" />
                    <add header="header2" />
                </allowHeaders>
                <allowMethods>
                     <add method="DELETE" />
                </allowMethods>
                <exposeHeaders>
                    <add header="header1" />
                    <add header="header2" />
                </exposeHeaders>
            </add>
            <add origin="http://*" allowed="false" />
        </cors>
    </system.webServer>
</configuration>`

Put the file on wwwroot!

**Comment by adolfintel** [comment]
Thanks, I'll add this to the wiki
