### ISSUE TITLE
Suggestion: HashIDs for telemetry links

### ISSUE THREAD

**Issue by Dubz** [adolfintel/speedtest#186]
## Description
Rather than having links like the following:
https://example.com/speedtest/results/?id=1
You would get a link like:
https://example.com/speedtest/results/?id=ejRe
(This is an empty salt with a minimum length of 4)

## Why it should be implemented
Block the ability to increment results ID number to harvest user data

## Implementation suggestions
Customization for your own salt, minimum length, and alphabet of characters (leaving the default to the plugin's)

## Website
https://hashids.org/

This does not require any changes to the database. Simply change the given link in the results to the encoded version, then decode the ID from the $_GET variable on visit.

**Comment by adolfintel** [comment]
The idea is good, but I don't want an external dependency on the project so I'll try to implement the idea myself when I have time.
