### ISSUE TITLE
Problem with many backends servers

### ISSUE THREAD

**Issue by History73** [adolfintel/speedtest#187]
Hello,
I have 6 backends servers and when everyone is online all work very well.
If one of the backends servers is offline then  can not choose from the others.
The  circle turns around continuously and can not select one of the other servers.

Thanks,

**Comment by adolfintel** [comment]
Hi,
I can't replicate your problem. One of my demo points is down right now but the test works just fine.
If you can, send me a link to your test at info@fdossena.com (or here) so I can check it.

**Comment by History73** [comment]
Ok,
after about 40 seconds the options are displayed but it is Much time.The user will not wait for so long...
Now i have shutdown one server and you can see the broblem. The site is www.speedstress.net

**Comment by adolfintel** [comment]
Yes, I see. Your server in Atlanta isn't actually down, it's just not responding so the server selector waits until the timeout is triggered (took 7 seconds on my machine but varies between browsers).
We could enforce a shorter timeout client side in the server selector but it had problems with older browsers.
If you want to try it anyway, edit server_selector.js, you'll see that some lines of code are commented out, those enforce the timeout. Let me know if it works for you

**Comment by adolfintel** [comment]
Actually, try this one
[test.zip](https://github.com/adolfintel/speedtest/files/2699631/test.zip)

**Comment by History73** [comment]
I have upload your test server_selector.min.js but now  i can not select any server...Remain in a state -->Selecting a server...

**Comment by adolfintel** [comment]
Try it now
[test2.zip](https://github.com/adolfintel/speedtest/files/2699694/test2.zip)

**Comment by History73** [comment]
Yes super, now it's ok. Thank you very much for the quick response!

**Comment by adolfintel** [comment]
That's good. It needs a bit of testing before I push it though

On December 20, 2018 5:46:46 PM GMT+01:00, History73 <notifications@github.com> wrote:
>Yes super, now it's ok. Thank you very much for the quick response!
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/187#issuecomment-449061994

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
