### ISSUE TITLE
null reference exception in download test function.

### ISSUE THREAD

**Issue by jeremeguenther** [adolfintel/speedtest#189]
## Description
On line 227 of speedtest_worker.js
xhr[i] = x
an error is thrown because xhr is null.  It looks like this is due to this script not localizing the xhr variable, so when the download test has started all its timers then the upload test gets started and is wiping out the xhr variable for its own use because it is referencing the same variable.  Changing this to a localized variable fixes the issue.

up on line 219 change:
xhr = []
to:
var xhr_dl = [];

then update all local references to the new variable.

My guess is that because xhr is shared across all the functions this will result in similar race issues popping up in other places in the future as well.

On a side note: it would be great if the js lines were terminated by semicolons.

## Server
Every info you can provide about your server: web server, database, PHP version, ... as well as server-side speedtest settings
If possible, provide an URL to your speedtest so we can check it

## Client
This is in IE 11, running a local development instance on IIS Express.  I am currently working on integrating this script into a .net site I am developing.

## Steps to reproduce
* Do this
* Do that
* Bad stuff happens

## Expected behaviour
What should have happened

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful

**Comment by adolfintel** [comment]
I'm unable to reproduce the problem. I assume that for some reason the function clearRequests is called between lines 219 and 227 by another test? But it shouldn't happen because clearRequests is always called before a test is declared "done". Weird...
Does it change anything if you replace line 179 with ```xhr=[]``` ?

**Comment by jeremeguenther** [comment]
I reversed my fix and the error is no longer occurring, race conditions can be really hard to re-create consistently.  If I can get it to trigger again then I will attempt your suggestion to see if that method is the issue.

**Comment by adolfintel** [comment]
Yea, it's really weird. It's technically possible for this to occur if an XHR for some reason takes several seconds to stop, but as far as I know, they stop instantly.
Let me know if you find anything.
