### ISSUE TITLE
A manual shift feature server

### ISSUE THREAD

**Issue by Ret32** [adolfintel/speedtest#193]
## Description
Add a function to manually select a server from a specified list of servers

## Why it should be implemented
If you have a large list of servers, you must select a specific server, not one that is automatically selected. And to change the server you need to reload the test page. I propose to implement this list of servers in the form of a drop-down list. After selecting the server, the test will be performed from this server, provided that it is available, otherwise an access error will be displayed. Automatic selection of servers you can leave, the main thing that then it was possible to change manually.

**Comment by adolfintel** [comment]
It's already implemented in the mpot branch, see example-manualSelection
