### ISSUE TITLE
Low Uplink Speed

### ISSUE THREAD

**Issue by miraikuro** [adolfintel/speedtest#194]
## Description
Very Low Uplink Speed

## Server
apache2
php 7.2
ubuntu 18.01
I have 1Gbps bandwidth from server to client the downlink speed always shows 980-ish Mbps meanwhile the uplink speed is never exceed 100Mbps.
What could be the issue?
I already follow all the instruction to optimize apache, php and tcp setting.
Did I miss something?
I tried this in 2 system and they have same behavior, low uplink speed.

## Client
Any clients

Please help.

Thank you.

BR//
Adi

**Comment by adolfintel** [comment]
Please don't open issues for troubleshooting, they're for bugs. Write me at info@fdossena.com and I'll help you figure it out.
