### ISSUE TITLE
Docker options

### ISSUE THREAD

**Issue by pmow** [adolfintel/speedtest#195]
Hello, Love the project,

Troubleshooting an issue I noted the teste was by default, multithreaded.  I tried using the options, which are usually passed along to the container at runtime like so:
`-e TIME_DL_MAX=5`
or
`-e CONFIG_TIME_DL_MAX=5`

Is passing config options to the container supported (in which case I'd be happy to edit the wiki)?
I can make my test single-threaded by editing the docker container directly, but obviously the changes would be overwritten.

**Comment by adolfintel** [comment]
Hi.
The docker port is very basic actually, it's just a simple installation with the default settings and no telemetry; to change the settings you have to edit the container.
I will make it more flexible in the future, but I'm not much of an expert on docker so if you have more experience and you have some time to spare, feel free to send a PR.
