### ISSUE TITLE
Nginx (+lua module) backend

### ISSUE THREAD

**Issue by julienschmidt** [adolfintel/speedtest#197]
I chose to implement a minimal backend directly in nginx (with help of the lua module), instead of using the existing PHP or node backends.
See here: https://gitlab.stusta.de/stustanet/speedtest/blob/stustanet/nginx/speedtest.conf

Are you interested in having this contributed upstream (here) somehow?
I'm not interested in actively maintaining a branch :)

**Comment by adolfintel** [comment]
Interesting. I suggest you fork the project if you can't actively maintain a branch. I'll mention it to future nginx users.
