### ISSUE TITLE
Issues with garbage file

### ISSUE THREAD

**Issue by Processeur** [adolfintel/speedtest#2]
Hi,

First of all, thanks for your bandwidth tester that I use since last week.

I tested on several environments : 

1)Linux Ubuntu(64) client, CoreI processor, at least 8Gig of ram with Chrome and Firefox (Internet direct access)

2)Windows 8.1(64) Client , Core2Duo processor, 2Gig of ram with IE11 and Chrome. (behind proxy)

I got some problem with your garbage file.

If I let the speed tester use the garbage.php file on any machine:

-With the previous release of your speed tester:
    -Download speed never went above 0.7kbps (even in local network)
    -Upload and Latency seems to be OK

-With last release:
 On linux machines: 
    -Chrome crash after the download.
    -Firefox slowdown the client PC as hell in download phase, needed to reboot.

 On Windows Machines: 
    -IE or Chrome  slowdown the client PC as hell in download phase, needed to reboot.

If I do a symlink do /dev/urandom (with command : ln -s /dev/urandom /var/www/speedtest-master/garbage.dat, and I replaced all references to garbage.php in garbage.dat in html and js files)on any PC and any browser, Download always get 0.00 mbits/s

If I generate a garbage.dat file with dd if=/dev/urandom of=/var/www/speedtest-master/garbage.dat count=10240 bs=1024. It seems to be ok for any browser on any machine.

But for very slow internet connection, download a 10MB file can be very long, that's why i'm interested by a working live generated garbage file.

One question: does the given results are the very last obtained value or the average speed?

Cheers

Proc.

**Comment by adolfintel** [comment]
garbage.php only works if you're going through a web server, otherwise you get that speed.
If you use a file full of garbage (I have a 100MB file linked in the readme file), PHP will not be required. You will still need to run it through a web server though.
Download and upload tests stop after 15 seconds, so don't worry about downloading the whole file.

**Comment by adolfintel** [comment]
I will try to replicate that problem with the new version, maybe it's an issue with web workers on Linux

**Comment by Processeur** [comment]
Hi Adolfintel,

Speedtest-Master is installed on an Ubuntu Server 14.04, with Apache2 and PHP5.

So I don't understand why garbage.php is not working, but if the tests stop after 15 seconds whatever happens, a dummy file (which I have already generated) ok for me.

Thanks for your answer.

If I can help to test your future releases, tell me.

**Comment by adolfintel** [comment]
That's very strange, I'm using Apache2 and PHP5 too.
Can you tell me more about how you're using the speed test? For instance, is the JS file in the same directory as garbage.php?

**Comment by Processeur** [comment]
So,

I'm using:

-Ubuntu 14.04 Server (64)
-Apache 2 2.4.7
-PHP 5.5.9

Apache2 Enabled modules:

 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cgi_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 proxy_module (shared)
 proxy_http_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)

Path for files:

Everything is in : /var/www/speedtest-master/
www-data owner of this directory and files inside.

Files totally untouched, but all references to garbage.php changed to garbage.dat as I got the problem previously described with garbage.php.

Tell me if you need anything else.

**Comment by adolfintel** [comment]
What happens if you try to load garbage.php directly from the browser? Do you get an error or an empty page?

**Comment by Processeur** [comment]
I'll give a try today, I was off yesterday.
