### ISSUE TITLE
nodejs Memory rises steadily

### ISSUE THREAD

**Issue by FishOrBear** [adolfintel/speedtest#200]
It's the same on both Windowns and Centos. I use pm2 to open the project.

![image](https://user-images.githubusercontent.com/19372111/53138065-fe1f4a80-35bf-11e9-9ddc-5b6eeffbaf7e.png)

**Comment by adolfintel** [comment]
122mb isn't much for a node application, is there a memory leak or does memory get deallocated properly when the garbage collector is triggered?

**Comment by FishOrBear** [comment]
May be a problem with nodejs GC, or a problem with pm2.

**Comment by adolfintel** [comment]
If it turns out to be a real memory leak, let @dunklesToast know, it's his branch after all.

**Comment by dunklesToast** [comment]
This could be a problem with the way I generate the garbage. I will fix it in the next version

**Comment by FishOrBear** [comment]
@dunklesToast  Well, I think the memory usage of the node version is too large.
