### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by elric72** [adolfintel/speedtest#203]
First of all, your application is really useful.
My question is : Is it plan to implement a multilingual solution in this apps ?
It could be very interresting if you have people who speak different languages that could use the same app.

Thank you in advance for your feedback
Regards
David

**Comment by adolfintel** [comment]
You can implement this in the front-end.
The examples are in English for convenience but you can use whatever language or localization framework you want. There are a couple of hardcoded strings in getIP.php (errors) but nothing that the user will normally see and I plan to remove them in future releases.

**Comment by elric72** [comment]
Ok, do you already have a template ?
If you want I can do the french translation.

David

Le jeu. 28 mars 2019 à 19:54, Federico Dossena <notifications@github.com> a
écrit :

**Comment by adolfintel** [comment]
You can start from one of the examples and change the strings.
They don't use any localization framework, it's just text on the page.

**Comment by Nottt** [comment]
how one would do this with the docker?

**Comment by dunklesToast** [comment]
Fork [this](https://github.com/adolfintel/speedtest/tree/docker) branch using git and then edit the strings. After you've done that you need to build the container again and then you can deploy it with docker. You do not need to publish it to docker hub.
