### ISSUE TITLE
Test speed of a single connection

### ISSUE THREAD

**Issue by Nottt** [adolfintel/speedtest#207]
## Description
A similar test to speedtest.net that allows testing the speed of a single connection

## Why it should be implemented

This allows us to use this speedtest to test for speeds for live streaming, single file downloads, over a VPN

## Optional: screenshots

![image](https://user-images.githubusercontent.com/13532436/57962047-aa37af80-78e9-11e9-9135-b6f9b9b1673d.png)

**Comment by dunklesToast** [comment]
Changing the `xhr_dlMultistream` [parameter](https://github.com/adolfintel/speedtest/blob/master/speedtest_worker.js#L53) and the `xhr_ulMultistream` [parameter](https://github.com/adolfintel/speedtest/blob/master/speedtest_worker.js#L53) in the [speedtest_worker.js](https://github.com/adolfintel/speedtest/blob/master/speedtest_worker.js) to 1 should do the trick. If you want to let the user choose, make a button with some JavaScript function which changes this! For faster Site loading don't forget to minify the JS afterwards!

**Comment by Nottt** [comment]
How to change those things using docker? 

Or is better to fork and add it to my dockerhub?

**Comment by dunklesToast** [comment]
You could edit them in your containers filesystem. Please do not re-publish this on dockerhub. You can build it on your server and then simply deploy this container. I think the service needs to be more able to be configured via environment variables. I can add this to the nodejs version

**Comment by Nottt** [comment]
I can try to create a docker that allows to set this kind of stuff with variables.... let me know what kind of things you'd like to change with variables and where. 

But I only know how to create containers with s6-overlay so it would be a very different architecture than yours currently...

**Comment by adolfintel** [comment]
Just a quick clarification, @dunklesToast 's answer is correct, but modifying speedtest_worker.js is the brutal way to change the test settings, you can pass your custom settings when you create the worker. See this: https://github.com/adolfintel/speedtest/wiki/Changing-the-test-settings

**Comment by Nottt** [comment]
@adolfintel so a docker that generates a html with your custom settings passed as variable is the way to go?

**Comment by adolfintel** [comment]
Yes, that would be the proper way, at least until I make a better docker version with proper arguments

**Comment by Nottt** [comment]
Sorry but I think I'm going to have to republish this on dockerhub. I need to deploy this in multiple servers, and I see no other practical way than forking the docker and editing it and publishing it...

I could try to find time to rebuild a docker from 0 which is more customizable, but without knowing if it would be accepted, I'd just end up publishing it for my use anyway so better to take the fastest approach...we all have little time and too many projects :(

**Comment by adolfintel** [comment]
@Nottt Sure, the project is open source for a reason, as long as your fork is LGPLv3 it's a perfectly legit use case.

**Comment by Nottt** [comment]
Is the nodejs install good enough for use? It seems to be way faster to install, so I could spin up a docker much faster than fitting the other dependencies into a single docker. 

In fact using the pre-compiled binaries, would be the easiest, way to put into a docker, but I can't find them in the release page? Are they full static, meaning it's just execute them inside a docker and it's ready?

**Comment by adolfintel** [comment]
The node version doesn't have all the features, but it has no problems as far as I know. @dunklesToast is the maintainer so maybe he can answer your question better.
