### ISSUE TITLE
Default to reporting measured rates and give the estimates of the gross rates as additional number

### ISSUE THREAD

**Issue by moeller0** [adolfintel/speedtest#209]
## Description
Change the default value for overheadCompensationFactor from 1.06 to 1.0, as without knowing the actual encapsulation used by a given client-server pair this is at best an estimate wich will not be correct for everybody. But even if not correct for everybody it still will be useful for quite a number of folks so why not report both like:

measured net-rate: XXX Mbps
estimated gros-rate: YYY Mbps

That will combine precision with utility ;) 

## Why it should be implemented
Everybody would benefit from this, as it will both make the test rsults directly comparable with traditional on-line speedtests like ookla's and it will let the user know what was actually measured and what was estimated.

**Comment by adolfintel** [comment]
It's an idea, I'll keep this in mind for the next version ;)
