### ISSUE TITLE
Safari mpot Content-Encoding is not allowed

### ISSUE THREAD

**Issue by josh48202** [adolfintel/speedtest#211]
## Description
When running tests using the mpot branch, during the upload process i receive about 2,000 errors. Resulting in a ridiculous upload speed around 300Mbps. This is on a Safari Browser on OSX. Testing with Firefox and Chrome on same device results in normal 50Mbps upload speed.

> Failed to load resource: Request header field Content-Encoding is not allowed by Access-Control-Allow-Headers.

## Server
I have two backend servers. One running on NGINX and php and the other apache and php both php version 5.6

## Client
OSX Safari

## Steps to reproduce
* Running normal speed test on mpot branch using Safari on OSX.

## Expected behavior
* Expected speed should be around 50Mpbs

**Comment by adolfintel** [comment]
You're not the first one to report this with nginx.
The only thing I can suggest is that you make sure that the CORS headers you're sending match the ones in the PHP files.

**Comment by adolfintel** [comment]
Are you sure? Does it happen on my demo? https://speedtest.fdossena.com/mpotdemo

**Comment by josh48202** [comment]
I get a similar error but for content-type instead of content-encoding.

these are the headers from the backend server which match the php files.
![Screen Shot 2019-05-23 at 11 27 33 AM](https://user-images.githubusercontent.com/6795008/58265548-e5087000-7d4d-11e9-801d-7ee8c914efff.png)

**Comment by adolfintel** [comment]
Shit, they must have broken CORS again.
Unless you changed something, during the upload test it should receive these headers:
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST
Access-Control-Allow-Headers: Content-Encoding
```
As you can see I explicitly allow the Content-Encoding header so I don't see what it's complaining about. Content-Type is also there and perfectly valid so go figure.

I don't have a mac to test this on unfortunately, so testing it is a bit hard for me. Can you do some investigation about this on your machine? Maybe changing the order in which headers are sent?

**Comment by josh48202** [comment]
I have copied all the php files exactly from the backend folders in the repo to my backend servers. I will play around with the headers more but didn't have much luck as i tried before starting this issue.

**Comment by josh48202** [comment]
I hadn't tried changing the order as you suggested before but i moved the access control headers to the top under the 200 ok header and then added content-type to the allow headers and that appears to have removed the errors and gave me a more realistic upload speed.

`header( "HTTP/1.1 200 OK" );
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST');
header('Access-Control-Allow-Headers: Content-Encoding, Content-Type');
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
header("Connection: keep-alive");`

**Comment by adolfintel** [comment]
Safari never ceases to amaze me with its bugs.

Do you want to send a PR with the fix so you'll appear in the contributors?

**Comment by josh48202** [comment]
#212 
I created a pull request. It was my first pull request so hopefully i did it correctly.

**Comment by adolfintel** [comment]
Yes, you did it right.
I'll test it on other browsers before merging it tomorrow.

Thanks for the help.
