### ISSUE TITLE
Feature request: show date and time in results

### ISSUE THREAD

**Issue by tuxayo** [adolfintel/speedtest#215]
## Why it should be implemented
It helps to keep track of the results and for example compare them to logs or graphs to know if an issue was caused by a poor internet connection, or vice versa.

**Comment by tuxayo** [comment]
Thanks for making the only libre in-browser speed test that I could find :D

**Comment by adolfintel** [comment]
Are you talking about the generated image at the end of the test or the telemetry results page?

**Comment by MagTun** [comment]
Yes, it would be nice to have the date and time on the generated image at the end of the test. I have to keep them as a proof of my internet speed and it would really help if this image are timestamped.

**Comment by adolfintel** [comment]
The generated image will be redesigned with the next update, I'll think about adding this
