### ISSUE TITLE
time_dl_min option?

### ISSUE THREAD

**Issue by bleomycin** [adolfintel/speedtest#216]
## Description
If possible it would be great to have an option to require tests to run for a minimum duration. Playing with time_dl_max no matter what setting I apply the test only runs ~5 seconds (on a gigabit connection). This isn't long enough to counter the "speed boost" nature of many residential isp's, often after 10-20 seconds actual speeds will slow. 

Thanks for the great software!

**Comment by adolfintel** [comment]
You can set time_auto to false for the moment. I'll see if I can add a time_dl_min setting in the next release
