### ISSUE TITLE
Disable IP Logging for Privacy

### ISSUE THREAD

**Issue by Wlanfr3ak** [adolfintel/speedtest#222]
## Description
logging_ip_adresses (true/false) in telemetry_settings.php

## Why it should be implemented
Option to disable IP-Adresses Logging into Database for privacy reason and national laws

## Optional: implementation suggestions
I think a true/false switch at the telemetry_settings.php would be perfect

**Comment by adolfintel** [comment]
This sounds like a good idea, I'll add this to the projects and implement it in the next update
