### ISSUE TITLE
Capture the GPS location or Browser location. 

### ISSUE THREAD

**Issue by leonleslie** [adolfintel/speedtest#223]
## Description
Capturing the browser location GPS location using the HTML Geolocation API to more accurately locate the user's position.

## Lets implement this feature because
Capturing the browser location will improve support for mobile devices or assist with network performance test surveys. 

## Optional: implementation suggestions
As of Chrome 50, the Geolocation API will only work on secure contexts such as HTTPS. Sites hosted on a non-secure origin (such as HTTP) which requests to get the users location will no longer function unless it is localhost.  The system should be able to identify if such is the case.  This feature should require administrator configuration and will require the user to allow sharing of their location.  This should be implemented with a logging_gps_addresses (true/false) in telemetry_settings.php to ensure that privacy could be maintained. 

The GPS coordinates retrieved could be geocoded to return a more accurate address.

**Comment by adolfintel** [comment]
This would be a privacy nightmare.
There is no reason why test owners should know the GPS location of their users, and test owners would have to be GDPR compliant and I wouldn't count on that. If you're an ISP you don't need to know the GPS location from the test, you can match the IP in your internal database.
If you really want this implemented, you'll have to fork the project, sorry.
