### ISSUE TITLE
The start button  doesn't start the speed tester after start-stopping it, and then, double tapping on it. 

### ISSUE THREAD

**Issue by realrufans** [adolfintel/speedtest#224]
## Describe the bug

The start button  doesn't start the speed tester after start-stopping it, and then, double tapping on it. 

## To Reproduce

 * Go to http://speedtest.fdossena.com/
* Click to start the speed tester, then, click again to stop it. 
* Double tap on the button
* Try to start the speed tester again
* Watch the button not starting. 

## Visual Display

![MNML-July8-0916-1562573861343.gif](https://cdn.steemitimages.com/DQmYsFxqKVu6NLJEihbBsoYteoM6zj5muJM2NWpCrJraZ6v/MNML-July8-0916-1562573861343.gif)

## Expected behavior

I expected the start button to respond to click regardless of the amount taps on the button.

 
## Environment

* Browser version: Chrome 74.0.3729.136
* Operating system: Android 8.1.0

**Comment by adolfintel** [comment]
I can't reproduce the problem. Can you connect it to your PC and see if there are errors in the console?

**Comment by realrufans** [comment]
The reported bug was tested on a mobile device. However, I'm not really good with the console menu. But when I tried testing the bug on my PC, the button didn't start the speedtest on the first click.

```(index):92 Uncaught TypeError: s.getState is not a function
    at updateUI ((index):92)
    at frame ((index):112)```


![image](https://user-images.githubusercontent.com/33923021/60797299-ec9da000-a166-11e9-9273-d3dff04e8686.png)

**Comment by adolfintel** [comment]
It could be caused by the fact that you pressed the Start button before speedtest.js was fully loaded. I will add a check for that

**Comment by realrufans** [comment]
Okay, but it doesn't still work after waiting for minutes after accessing the page.

**Comment by adolfintel** [comment]
Does it work if you press Ctrl+F5?

**Comment by realrufans** [comment]
I just did (Chrome & Firefox) still not running.

https://www.youtube.com/watch?v=lfaVjNL4eik&feature=youtu.be

**Comment by adolfintel** [comment]
I really cannot replicate your problem on any browser. Do you have anything installed that could cause problems? Antivirus software, VPN software, proxies, data saver, ...?

**Comment by realrufans** [comment]
None of that is installed. I am still surprised that it worked on my mobile Chrome and not for my PC. Although, on mobile, it doesn't start again after double tapping on the button. 

I guess I am the only one with these issues. I will have to close this report. Thanks.

**Comment by adolfintel** [comment]
Could it be some extension that you have installed? I don't recognize most of them

**Comment by realrufans** [comment]
I have extensions installed on my chrome, but nothing installed on Firefox, and it didn't work with it.

Maybe I should just close the report as it's just happening to me only. Hoping someone    confirms this.
