### ISSUE TITLE
Results Image Not Displaying

### ISSUE THREAD

**Issue by Daemonslayer2048** [adolfintel/speedtest#225]
## Description
After running a speedtest an image is not displayed. The box outline along with the broken image logo instead is displayed.

## Server
Web Server: Httpd (Apache) 2.4.6
Database: MariaDB 5.5.60
PHP: 5.4.16
My index.html is a copy paste of example-singleServer-full.html. 
URL: https://speedtest.hanafin.pro

## Client
So far Firefox on Fedora OS or Chrome and Firefox on Android

## Steps to reproduce
Intstall on CentOS container (note: container not VM)

## Possible reason for failure
I suspect the I would be missing some specific php package used to render the image. Containers often come as very bare bones install and I suspect I am simply missing a specific PHP package.

**Comment by adolfintel** [comment]
The image fails to generate due to a 500 server error. The most likely reason is that you don't have FreeType2 installed (and its PHP module enabled). Fix this and try again.

P.S. Please don't open issues for troubleshooting, this is not a bug.

**Comment by Daemonslayer2048** [comment]
By the way, you were correct the packages freetype and php-gd on CentOS were missing. I apologize for completely missing the troubleshooting section (I must be blind, you even pinned it) and coming here. The application is great though, awesome job.
