### ISSUE TITLE
Unable to see share result screen

### ISSUE THREAD

**Issue by djabu** [adolfintel/speedtest#228]
## Description
Not able to see the share result screen post test

## Server
Apache/2.4.33 (Win32) PHP/7.0.30 
Mysql Server version: 10.1.32-MariaDB 

## Client
Chrome Version 75.0.3770.142

## Steps to reproduce
Post tests all I get is the result of the test and the IP Address field underneath. The share result section is not visible. 
Results are getting stored in the database and we are able to see that via stats.php page and the URL for results results/?id=1 itself is working.

## Expected behaviour
Share results should show up post test. 

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful

**Comment by adolfintel** [comment]
Please don't open issues for troubleshooting, this is not a bug.

Since you can access results/?id=1, the feature is working properly, so you're either using an example that doesn't have the results sharing, or something is failing after the result has been stored (check the server logs for telemetry.php).

**Comment by djabu** [comment]
My bad for logging this as a bug. Im using example-multipleServers-full and I can see the code for sharing under the shareArea. Sorry dumb question, how do I check the server logs for telemetry.php?

**Comment by adolfintel** [comment]
That depends on your system, it's usually under /var/log/apache2/error.log

**Comment by djabu** [comment]
ok it says
 'D:/xampp/htdocs/speedtest/empty.php' not found or unable to stat, referer: http://xxxxx/speedtest/

Isn't the empty.php under the backend directory? 

I've updated the speed test server to this - server:"//xxxxx/speedtest/backend/",

**Comment by adolfintel** [comment]
empty.php has nothing to do with your problem.
If you give me the URL to your test maybe I can see the error.

**Comment by djabu** [comment]
Im running this on a corporate network which is behind a firewall. Dont know if this helps, I've attached the browser console messages. 

![test](https://user-images.githubusercontent.com/20253776/62275248-e5776280-b484-11e9-8828-a8ba024f87a9.PNG)

**Comment by adolfintel** [comment]
That could be the problem. Did you make changes to the example?

**Comment by djabu** [comment]
I did, apart from adding the server information, I removed the ping and jittery display code below:
`	<div class="testGroup">
		<div class="testArea">
			<div class="testName">Ping</div>
			<div id="pingText" class="meterText"></div>
			<div class="unit">ms</div>
		</div>
		<div class="testArea">
			<div class="testName">Jitter</div>
			<div id="jitText" class="meterText"></div>
			<div class="unit">ms</div>
		</div>
	</div>`
I can restart again just to be sure.

**Comment by djabu** [comment]
Ok i get why that is not working now. Looks like I need to remove more than just the above code to get rid of Ping and Jitter as the share results is also referring to this information. In our case, ICMP ping would really help instead of HTTP, that is why we removed it.

**Comment by adolfintel** [comment]
You can't just remove parts of the UI without also removing the code that updates that.
Start over, this time remove the JS that updates the ping/jitter indicators, and disable the ping test properly (see [custom test settings](https://github.com/adolfintel/speedtest/wiki/Making-a-custom-front-end#test-parameters))

**Comment by djabu** [comment]
great. went through the parameters, not able to find find a way to disable just the ping test. 
Can only see telemetry_level setting.

**Comment by djabu** [comment]
never mind. got it working. Thank you so much.
