### ISSUE TITLE
Add extra share results line with bbcode

### ISSUE THREAD

**Issue by Wanabo** [adolfintel/speedtest#229]
## Description
There is only a plain link shown. Request a second line with BBcode IMG code.

## Why it should be implemented
End users who wish to share their result on other websites. Especially forums.

## Optional: implementation suggestions
Sorry I tried, but ended up here.

## Optional: screenshots
Look at these two screenshots. First screenshot marks the spot for the extra BBcode IMG code. Second screenshot is an example I made which I hope you will implement.

![Image of result and position for extra line](https://i.ibb.co/xfVLnPs/add-extra-code.gif)
![Image of wish for extra line](https://i.ibb.co/5B3DSRn/bbcode-img-wish.gif)

**Comment by adolfintel** [comment]
It can be done easily, but it's just an example, you're supposed to use it as a base and make your own frontend around it. Anyway, I'll add it the next time I update it.

**Comment by Wanabo** [comment]
That would be great! I tried, but failed. 
Any hints were and how to approach this?

**Comment by adolfintel** [comment]
You just add another text field where you want it, let's give it `id="bbcode"`, then find this line:
```
var shareURL=window.location.href.substring(0,window.location.href.lastIndexOf("/"))+"/results/?id="+testId;
```
This generates the URL to the image, so below it, add:
```
I("bbcode").value="[img]"+shareURL+[/img]"
```

**Comment by Wanabo** [comment]
Adding I("bbcode").value="[img]"+shareURL+"[/img]"; does not seems to work. The share results is gone.

But it might be for nothing, because the code below does not show an image on another website. Used of course a real id.
[url=http://speedtest.fdossena.com/results/?id=xxxxxxxx][img]http://speedtest.fdossena.com/results/?id=xxxxxxxx[/img][/url]

**Comment by Wanabo** [comment]
Edited my previous post heavily a couple of times as I was struggling to make bbcode to work.
It seems to work, but it is dependent on what type of bbcode to html converter a website uses.
To make it  more general compatible, please take a look at my suggestion in the previous post.

With websites that accept html code there is no problem. It seems to be bbcode that ruins the party.
