### ISSUE TITLE
Wildly Inaccurate Upload - Slower Connections

### ISSUE THREAD

**Issue by mattmartincouk** [adolfintel/speedtest#23]
We've been testing this and have repeat reports from people on slower connections (1Mb up) that this is mis-reported by a massive amount.

My test line which is 1Mb up also, gives a result of 2.6Mb - which is impossible.

Any obvious cause for this?

**Comment by adolfintel** [comment]
I have a 1mbit upload and I can assure you that it's accurate. I also collect a telemetry from my site and I haven't seen unusual values since Version 4.1 was released.

Some possible causes for what you're experiencing are:
-Buffering: is there a proxy in between? unusually long queues on any of the servers involved?
-Lag spikes: your server may be receiving data in big chunks instead of a nice flow (for instance because it's lagging)
-Test too short: all computers do some buffering, which causes an inaccurate speed reading at the beginning of the test, but then it stabilizes. I suggest you run the test for at least 15 seconds.

If there's anything more that you can tell me, I might be able to help you.

**Comment by mattmartincouk** [comment]
I'm not so sure.

We emailed this out to a few of our customers - each one reports the same thing. Upload is wildly and massively over what the connection is capable of. I have two connections at home, one fast - which is more accurate and the other slower which is not.

- There are no proxies for any users.
- We are the ISP and there are no latency issues. Latency range in the 8-30ms
- We left the default which is 15 seconds but also tried 30 too.

Latency test also appears to be lower than the actual line is capable of. My test showed 12ms but my actual line is 16ms.

In comparison, the speedtest.net HTML5 tester gave results matching to line (on par with other speedtesters).

For example, http://scrn.at/rBBKr.png
This user is on a 16.8Mb connection with 1.2Mb upload and their base latency is 27ms.

Speedtest.net (both flash and HTML 5 testers are good - the flash base tester is hosted on the same server as yours to give similar results) and then your tester - vastly different.

**Comment by adolfintel** [comment]
Can you try running the test that's on my site?
http://speedtest.fdossena.com/

**Comment by mattmartincouk** [comment]
Would love to but your site appears not to work on several connections - including via mobile phone.

speedtest.fdossena.com refused to connect.

**Comment by adolfintel** [comment]
What the heck is going on?
Can you give me your country and IP so I can report it to my hosting? Thanks

**Comment by mattmartincouk** [comment]
193.105.150.x - it'll come from various address.

Mobile phone varies and changes so no point giving that.

**Comment by adolfintel** [comment]
Thanks. XILO Communications, right?

**Comment by mattmartincouk** [comment]
Correct

**Comment by adolfintel** [comment]
I have reported this to my hosting provider. Sorry about that :(
See if you can access this one: http://isochronic.io/test/

**Comment by mattmartincouk** [comment]
Same issue. Traceroute if it helps.

traceroute to isochronic.io (89.40.172.38), 64 hops max, 52 byte packets
 3  a4n-dc1-gw.v-1002.rtr-0.dc1.shf.uk.as44574.net (31.13.6.246)  2.001 ms  14.924 ms  4.998 ms
 4  ask4-dc1-gw.v-2063.dc1.shf.uk.as44574.net (78.109.176.89)  1.519 ms  1.424 ms  11.643 ms
 5  man-xmr-dc1-xmr-w1-2.ask4.net (81.23.49.115)  4.495 ms  5.183 ms  4.504 ms
 6  xe-0-3-0-ucr1.mcr.cw.net (195.89.254.237)  4.642 ms  4.972 ms  4.884 ms
 7  ae4-xcr1.man.cw.net (195.2.28.69)  13.919 ms  10.383 ms  9.784 ms
 8  ae7-xcr1.bkl.cw.net (195.2.30.138)  9.441 ms  9.500 ms  9.218 ms
 9  ae1-xcr1.hex.cw.net (195.2.24.150)  8.788 ms  10.736 ms  9.206 ms
10  lag-10.ear1.london1.level3.net (4.68.72.93)  9.279 ms  9.279 ms  9.301 ms
11  ae-119-3505.bar2.milan1.level3.net (4.69.159.114)  70.998 ms  29.014 ms
    ae-120-3506.bar2.milan1.level3.net (4.69.159.118)  28.960 ms
12  212.73.241.250 (212.73.241.250)  147.557 ms  214.088 ms  218.660 ms
13  * * *
14  94.198.103.6 (94.198.103.6)  31.323 ms  31.416 ms  30.911 ms
15  * * *
16  *

**Comment by adolfintel** [comment]
Yes, netsons seems to be blocking your ISP. I have sent them an email, let's wait.
Meanwhile, you can try setting up the speedtest on github pages or some other free hosting that's not shit and see if you get the same result.

**Comment by mattmartincouk** [comment]
Set it up at http://speedtest.net.uk/html5/ which is local to us - thats where the result was from.

**Comment by adolfintel** [comment]
I'm getting inaccurate results from your server too, and lag spikes. You sure your server is set up properly?

**Comment by mattmartincouk** [comment]
I don't see how it wouldn't be. http://speedtest.net.uk has been running on it for about 5 years and is as accurate as speedtest.net (of which we host three nodes) with the same results.

Potentially just due to your local and routing in-between us.

**Comment by adolfintel** [comment]
I don't know, it could be. The only other thing you could try is setting xhr_ulMultistream to 1, or play around with it until you get a more accurate result.
Still, I don't think the problem is related to the test itself: it's been up for over a year, if it was that inaccurate, there would be a thousand issues open.

**Comment by dennore** [comment]
i think your post size on server is not configured correctly.. my server is running fine with this code
