### ISSUE TITLE
Result sharing not working with nginx

### ISSUE THREAD

**Issue by jordanrenker** [adolfintel/speedtest#230]
## Description
I installed the speedtest program on my nginx/mysql/php7.2-fpm server. I can make tests correctly but when test finished the share speed test image has broken link.

## Server
Every info you can provide about your server: web server, database, PHP version, ... as well as server-side speedtest settings
Web server: NGINX 1.14.0 - apt-get install nginx-extras
PHP: PHP7.2 - apt-get install php-fpm
Mysql: V. 14.14 - apt-get install mysql-server
Distro: Ubuntu Bionic (fully up to date)
Internal network speed test: http://192.168.50.100/example-singleServer-full.html

## Client
Browser, OS, type of connection, unusual software, ...
Google Chrome on Windows 10

## Steps to reproduce
Install nginx; php; mysql; setup telemetry, change owner to www-data for all files in web directory; run speedtest

## Expected behaviour
It should show the share results image but I get broken link

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful
![Capture](https://user-images.githubusercontent.com/53881405/62662232-65983f00-b941-11e9-8eaf-e9dd9f932f14.PNG)

**Comment by jordanrenker** [comment]
I tried with apache2 and libapache-mod-php, the result sharing image and link works fine with apache, but I would like to use nginx.

**Comment by jordanrenker** [comment]
Sorry, I would also like to add I have this in my phpinfo. I read in another post that i might be missing freetype2..

Phpinfo:
FreeType Version | 2.8.1

**Comment by adolfintel** [comment]
Sorry for the late reply.
It looks like a problem with FreeType2, but if it's installed and enabled, there is some other problem.

Edit results/index.php, remove error_reporting(0), run the test, then check the server logs for errors.

**Comment by jordanrenker** [comment]
I created a new VM and installed the packages fresh so I can rule out it was a configuration issue on my end. The results still has a broken image link. I removed the error_reporting line from results/index.php. My nginx logs have an error about exceeding POST size, I have increased it to 50M and the error stopped. Now I am not seeing any more errors..
[error.log](https://github.com/adolfintel/speedtest/files/3481612/error.log)

**Comment by adolfintel** [comment]
Try downloading the generated image file and opening it in a text editor, there might be an error written at the beginning

**Comment by jordanrenker** [comment]
I cannot open results/index.php in chrome, I get error 500. Now I see an error in my log, This is the error :

2019/08/08 12:33:46 [error] 265#265: *166 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatetruecolor() in /var/www/html/speedtest/results/index.php:17
Stack trace:
#0 {main}
  thrown in /var/www/html/speedtest/results/index.php on line 17" while reading response header from upstream, client: 192.168.2.159, server: _, request: "GET /speedtest/results/index.php?id=9 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "192.168.2.141"

**Comment by jordanrenker** [comment]
@adolfintel I installed php-gd and uncommented ;extension=gd2 in my php.ini file. It is working now!

**Comment by adolfintel** [comment]
Line 17 is a call to imagecreatetruecolor, I thought it was a builtin function of PHP. I'll add that php-gd is required to the documentation.
