### ISSUE TITLE
Telemetry Configuration

### ISSUE THREAD

**Issue by jdtinsley88** [adolfintel/speedtest#231]
I have setup MySQL using the .sql file in the results directory and configured the telemetry_settings.php file correctly.

However, I am confused on configuring the speedtest files for telemetry.  I have pasted below a snippet of code from my index.html file.  Am I doing this correctly?

Appreciate all the assistance!

----
<script type="text/javascript" src="speedtest.js"></script>
<script type="text/javascript">

//INITIALIZE SPEEDTEST
var s=new Speedtest(); //create speedtest object
s.onupdate=function(data){ //callback to update data in UI
    I("ip").textContent=data.clientIp;
    I("dlText").textContent=(data.testState==1&&data.dlStatus==0)?"...":data.dlStatus;
    I("ulText").textContent=(data.testState==3&&data.ulStatus==0)?"...":data.ulStatus;
    I("pingText").textContent=data.pingStatus;
    I("jitText").textContent=data.jitterStatus;
    I("testId").textContnt=data.testId;
}
s.onend=function(aborted){ //callback for test ended/aborted
    I("startStopBtn").className=""; //show start button again
    if(aborted){ //if the test was aborted, clear the UI and prepare for new test
                initUI();
    }
}

function startStop(){ //start/stop button pressed
        if(s.getState()==3){
                //speedtest is running, abort
                s.abort();
        }else{
                //test is not running, begin
                 s.setParameter("telemetry_leve","basic");
                s.setParameter("url_telemetry","results/telemetry.php");
                s.start();
                I("startStopBtn").className="running";
                //s.setParameter("telemetry_leve","basic");
                //s.setParameter("url_telemetry","results/telemetry.php");
        }
}

//function to (re)initialize UI
function initUI(){
        I("dlText").textContent="";
        I("ulText").textContent="";
        I("pingText").textContent="";
        I("jitText").textContent="";
        I("ip").textContent="";
}

function I(id){return document.getElementById(id);}
</script>

**Comment by adolfintel** [comment]
Hi,
You seem to have mistyped telemetry_level, other than that, it looks ok. s.setParameter("url_telemetry","results/telemetry.php"); is not required because that's the default value.
