### ISSUE TITLE
Demo server is down!

### ISSUE THREAD

**Issue by adolfintel** [adolfintel/speedtest#232]
I know, it sucks that you can't try the speedtest before installing it, but I was getting so many connections that my site would go down on a hourly basis with a resource limit error. This should give you an idea of how many people were trying the test:
![image](https://user-images.githubusercontent.com/16307689/63292643-6d9f9980-c2c6-11e9-8012-9ca162207a33.png)

I will try to find some better hosting for the demo, or work something out with Consortium GARR, who seem to be interested in this project, but in the mean time, the speedtest demo will be down indefinitely.

I also had to take down the demo servers for the multiple points of test example.

Thanks a lot for your interest in HTML5 Speedtest!

**Comment by yylzcom** [comment]
OVH or Kimsufi maybe a good choice. They have unlimited bandwidth(only limit the port speed).

**Comment by tuxayo** [comment]
Congratulations for the success or your project! :D
That confirms a real need for libre speed test.

**Comment by tuxayo** [comment]
Suggestion: add a payment method to your Liberapay account: https://liberapay.com/fdossena/

And set a goal to fund the cost of hosting a new demo.

**Comment by tuxayo** [comment]
Suggestion: add a link to your Liberapay page in the webpage of the test: to suggest funding the demo hosting and the development of the software (at least to buy you a drink ^^)

**Comment by adolfintel** [comment]
You're right, I've added some donation links to the page.

**Comment by tuxayo** [comment]
Amazing! :D
 
You still need to link a Stripe or Paypal account to Liberapay.
Note that you can add both to maximize currency acceptable. And Stripe has less fees[1]

[1] From my experience: For a 12€ donation 0.88 with Paypal and 0.42€ with Stripe

**Comment by adolfintel** [comment]
Thanks for reminding me, I've added both.

**Comment by tuxayo** [comment]
It works! :D

Note: It's "Liberapay", not "LiberaPay"

Suggestion: write "Donate monthly with Liberapay" to make clear the difference with Paypal and instigate users to contribute in a more predictable and sustainable way for you.

**Comment by adolfintel** [comment]
Good news!
Thanks to the awesome contributions of Consortium GARR and B2B Risk, who offered completely free hosting for us, the demo is back up.

https://speedtest.fdossena.com
