### ISSUE TITLE
results page for node.js

### ISSUE THREAD

**Issue by huhsame** [adolfintel/speedtest#233]
I want to import on my project based on node.js to get the speed result of users.
I couldn't find anything about results in node branch. 

*node version*
![image](https://user-images.githubusercontent.com/9151382/63825448-d3aab180-c995-11e9-9990-c9d1748c7bcc.png)

*stat page in php version*
![image](https://user-images.githubusercontent.com/9151382/63826241-1d48cb80-c999-11e9-94c1-b62da4d6ebeb.png)

If I want to get the data like php version, 
How can I do that? 

I'm okay without image, just want to get data. 
thanks

**Comment by adolfintel** [comment]
The node version is not feature complete yet. Telemetry and results sharing are currently not implemented.
