### ISSUE TITLE
wrong upload output ?

### ISSUE THREAD

**Issue by mitrasero** [adolfintel/speedtest#25]
hi 

the uploading calculation seems wrong, could you suggest ?
( on this link i get 8Mbps - https://fdossena.com/?p=speedtest/testnew.frag ) 
( but using the git code on my server, i get a 108Mbps....)

![image](https://cloud.githubusercontent.com/assets/25478428/25575501/af404efe-2e60-11e7-9209-443a9bfb6c68.png)

Great job by the way ! thanks

**Comment by adolfintel** [comment]
I'm gonna need some more information
-do you have a link to this server?
-what browser are you using
-server config, etc.
-proxy, firewall, etc. in between?

Also, check the speedtest on my site and see if you get the same result: http://speedtest.fdossena.com

**Comment by mitrasero** [comment]
- the site is on my internal network
-chrome Version 58.0.3029.81 (64-bit)
-my laptop is macosx
-to reach the website im not going through a proxy but only a nat

**Comment by adolfintel** [comment]
If it's in your internal network, 100mbps seems very legit. Anyway, what do you get from my website?

**Comment by mitrasero** [comment]
- my upload is only 8Mbps limited by isp...
- i want to use what you made to test speed in case there are problems on my server (you know, for troubleshooting)

**Comment by mitrasero** [comment]
ps again on your site i get good score ...

[ ps cant reach this link http://speedtest.fdossena.com/ but only this https://fdossena.com/?p=speedtest/testnew.frag
 ]

![image](https://cloud.githubusercontent.com/assets/25478428/25578067/f05ceede-2e73-11e7-832c-b44ab35426fe.png)

**Comment by adolfintel** [comment]
Good, so the speedtest itself is not the problem.
Here's a few thing you can do to troubleshoot:
-First of all, press F12 in your browser and monitor the network requests when you're running the test on your server. It is ok to see errors during the ping tests, but not during the other tests
-Second, how are you accessing your server? VPN, firewalls, proxies, etc. may have buffering and just queue your data, or even compress it, thus giving incorrect results.
-Third, check your server: this speedtest was only tested on apache, with no special configuration. As far as I know, your server must not request compression, and it must accept large POST requests (up to ~20mbytes)

**Comment by mitrasero** [comment]
ill try exposing my server to the internet and test without the vpn to rule out the vpn or proxy.

**Comment by adolfintel** [comment]
I bet it's the VPN software, it queus your request and your machine thinks it's already sent.
If you try to copy a file over Samba (network shared folders) via your VPN, I bet you get a peak at the beginning and then it slows down

**Comment by mitrasero** [comment]
i thought this would solve it but nope .... strange ...
you can also test it : 
http://34.208.90.117/


here :

![image](https://cloud.githubusercontent.com/assets/25478428/25578491/ded96bde-2e77-11e7-8953-28a6cceaf441.png)

**Comment by adolfintel** [comment]
Your test works from here. There must be something between your machine and the server

![2017-05-01 13_18_17-speedtest - chromium](https://cloud.githubusercontent.com/assets/16307689/25578619/c35210ac-2e70-11e7-926e-61c693e5c8b6.png)

**Comment by mitrasero** [comment]
ok thanks ! ill go ahead and check ! thanks for your help !

**Comment by adolfintel** [comment]
Any time. Let me know what you find.
One of these days I'll have to write a troubleshooting guide for this thing

**Comment by mitrasero** [comment]
ps can you tell me what is the file size it uploads ?

**Comment by adolfintel** [comment]
It uploads multiple 20mbyte chunks simultaneously

**Comment by mitrasero** [comment]
Thanks !

**Comment by anoymouserver** [comment]
I had the same issue.

Server: nginx (no internal network)
Browser: Firefox

The problem was, that the Nginx doesn't allow POST requests on static files (like the `empty.dat`) and answers each connection with `405 Not Allowed`.
I symlinked the `empty.dat` to `empty.php` and it worked..

**Comment by adolfintel** [comment]
Thank you, I'll rename empty.dat to empty.php in the next release then ;)
