### ISSUE TITLE
Pass values out of function(event){}.

### ISSUE THREAD

**Issue by fotisolgr** [adolfintel/speedtest#26]
Hello. You have created a really nice speed test. Is it possible to pass the  download speed, ping & upload speed final values out of the function(event)? And if so how can i achieve that? I want to send these final values to my server using an ajax post method.

I'm able to send these values using an ajax post method inside the function(event){} but it keeps sending these final values to my server over and over again . If i can't pass the values out of the function(event){}, how can i stop it from running for ever?

Thank you.

@adolfintel

**Comment by adolfintel** [comment]
Hi.
I assume you're sending them from the function that updates the page, right? If that's the case, send your ajax request here:
```
if(status>=4){
    clearInterval(interval);
    //send your request here
    ..rest of the code...
}
```

In example4.html, it's at line 75.

**Comment by fotisolgr** [comment]
**That was the solution.**

 I have got one more question for you. I'm running the test through http://localhost/path/to/my/file.html and i'm getting really big measurements. Is this normal?

**Comment by adolfintel** [comment]
Of course, it's normal, if you're using localhost, you're not going through the network
