### ISSUE TITLE
A way to reduce the amount of requests and the transferred MB?

### ISSUE THREAD

**Issue by fotisolgr** [adolfintel/speedtest#28]
Hello. For comparison reasons, I created 3 different speed tests using JS libraries. My first implementation was done by using [Nettest](https://code.google.com/archive/p/nettest/). My second implementation was done by using [Boomerang](https://soasta.github.io/boomerang/doc/) and the third implementation was done by using your method. In every implementation, when the test is finished, I send the calculated measurements back to my server. 

**By using [Nettest](https://code.google.com/archive/p/nettest/) the requests and the transferred MB are:**
![nettest](https://cloud.githubusercontent.com/assets/27365645/25759503/7ae484a8-31db-11e7-94a8-f3dc515feb77.png)

**By using [Boomerang](https://soasta.github.io/boomerang/doc/) the requests and the transferred MB are:**
![boomerang](https://cloud.githubusercontent.com/assets/27365645/25759535/9b06d48e-31db-11e7-89e2-1e43906056fc.png)

**By using your method the requests and the transferred MB are:**
![speedworker](https://cloud.githubusercontent.com/assets/27365645/25759558/b8ca9faa-31db-11e7-9399-3efe08b268af.png)

**Question:**
Is  there a possible way to reduce the size of the transferred MB without affecting the accuracy of the measurements calculated by your method?

Thank you.
@adolfintel

**Comment by adolfintel** [comment]
There is already a time limit that you can set (default 15s). I could add a limit on transferred data, but that would certainly affect precision on very fast and very slow connections.
Maybe a possible future improvement could be to automatically determine the length of the test

**Comment by fotisolgr** [comment]
Thanks!
