### ISSUE TITLE
Upload Not Working

### ISSUE THREAD

**Issue by aficustree** [adolfintel/speedtest#30]
Can you advise on where to check in apache for issues with the HTTP Post? I'm a bit of an apache amateur and having trouble finding where I can set the file. Everything works great except for the upload.

**Comment by adolfintel** [comment]
Try this:
-go to your speedtest page
-press F12 and go to network
-start the speedtest
-see if you get any error (like 403 or 404) during the upload test

**Comment by aficustree** [comment]
seems to be only an issue when connecting through a VPN tunnel. Very odd. Thanks for the hint.

**Comment by adolfintel** [comment]
Yeah, going through a VPN is known for breaking the upload test
