### ISSUE TITLE
About Ping values

### ISSUE THREAD

**Issue by forkgood** [adolfintel/speedtest#33]
Hello, I'd like to consult the Ping value problem. I tested a lot of servers and found that the CMD Ping value is 2 times the Ping value in the web page test results.
Is the Ping value tested in the web program accurate? Or is there a solution?

Here are some pictures:
Page Ping：http://imgur.com/PQgu2OS
CMD Ping：http://imgur.com/6ivYXFc

**Comment by forkgood** [comment]
Page Ping：About 150MS
CMD Ping：About 300MS

**Comment by forkgood** [comment]
solved.

**Comment by adolfintel** [comment]
Ok. As a side note, I should point out that there is no accurate way to measure ping via HTTP, so my test is just an estimate, it's the time it takes to download an empty file.
