### ISSUE TITLE
false result

### ISSUE THREAD

**Issue by arist0v** [adolfintel/speedtest#36]
Hello, i tried your speedtest apps on our server. I got strange result:
download 2 mbps
upload 69 mbps

and when using a different webrowser on the same computer i got totally different result.

**Comment by adolfintel** [comment]
I'm gonna need a some details to help you:
* Are you using a VPN? Proxy?
* What web server are you using?
* What browser?
* Can you send me a link to your test?

99% of the time, this is caused by incorrect server config or going through some kind of buffering like a VPN tunnel

**Comment by arist0v** [comment]
Hello, no vpn no proxy
hosted on iis 7.5.7600.16385
windows server 2008 r2
and is there a private way to send you the link?

**Comment by adolfintel** [comment]
Send it to dossenus91@gmail.com

Also, IIS is not supported, never tested it.

**Comment by arist0v** [comment]
just emailed it to you, will be very happy if you could help me make it work

**Comment by adolfintel** [comment]
Upload and ping tests look ok. Download is very low, how much bandwidth do you have?

**Comment by arist0v** [comment]
currently limited at 50 mbps(we are the ISP)

**Comment by adolfintel** [comment]
Ah there I found the problem.
garbage.php is missing

**Comment by arist0v** [comment]
it's in the same folder as the test

**Comment by arist0v** [comment]
on the server, speedtest.net oat 480.37mbps download and upload at 199.30

**Comment by arist0v** [comment]
i think we don'T have php on this server yet sorry

**Comment by adolfintel** [comment]
http://[ip]/speedtest-4.2.1/garbage.php
it 404s

**Comment by adolfintel** [comment]
Oh ok, that would explain it

**Comment by arist0v** [comment]
thank you and sorry always dumb thing :P

**Comment by adolfintel** [comment]
No problem, happy to help
