### ISSUE TITLE
Accuracy when latency is high

### ISSUE THREAD

**Issue by bjornfro** [adolfintel/speedtest#39]
Hi,

Seems latency and jitter measurements are not correct. At least not when testing over high latency.

Below are examples where the ping RTT is 260ms. 

Older version speedtest:

Latency 205.30ms, 123.30 ms jitter

Latest version:

Latency 424.31 ms, 251.06 ms jitter

Browser: 
Version 59.0.3071.104(64 bitar) Windows 7
Server: CentOS 7 with Apache

**Comment by adolfintel** [comment]
Make sure your server is sending Connection: keep-alive

**Comment by bjornfro** [comment]
True. I am sharing apache with another application that specifically had turned keepalived off. Disabled that and it looks a lot better:

261.31 ms, 11.76 ms jitter

So, no issue then ;-)

**Comment by adolfintel** [comment]
Ok. If you want to leave it off, you can just replace
```js
var instspd = (new Date().getTime() - prevT)
```
with 
```js
var instspd = (new Date().getTime() - prevT)/2
```
