### ISSUE TITLE
Tried and it collapses my browser

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [adolfintel/speedtest#4]
The computer becomes unusable.
I think it is due to a high use of CPU and memory.
Tested in a recent 8 core CPU with 8 Mb RAM.

**Comment by adolfintel** [comment]
Which browser and which server did you use?
Also, was it running locally or remotely?

**Comment by DavidPerezIngeniero** [comment]
Tested with Firefox and Chrome.
Server is Apache 2.2 under Linux.
Running remotely, i.e., server and client in different computers.
It's the 1st Javascript that manages to collapse my computer and browser in this way.

**Comment by adolfintel** [comment]
That's very weird, it's the same setup that I use.
Does [the test here](http://speedtest.adolfintel.com/) crash your machine too?

**Comment by DavidPerezIngeniero** [comment]
Your URL runs ok, the one that doesn't work is:

https://rdstest.fccma.com/test-velocidad/example1.html

**Comment by adolfintel** [comment]
Your server has data compression enabled. As a result, it's sending the client so much data it pretty much kills the browser.
Try downloading https://rdstest.fccma.com/test-velocidad/garbage.php and see how much data is sent.
If you cannot turn off compression, I suggest you use a big garbage file like the one linked in the readme, or a video.

**Comment by DavidPerezIngeniero** [comment]
OK, thanks!

**Comment by DavidPerezIngeniero** [comment]
Now it works.

How to disable for Apache:

```xml
<Directory /var/www/test-velocidad>
    <ifModule mod_gzip.c>
    mod_gzip_on No
    </ifModule>
</Directory>
```
