### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by j2ghz** [adolfintel/speedtest#41]
I see you have recently added docker support (#40)
Could you add it to Docker Hub as well, so we don't have to build it?

https://docs.docker.com/docker-hub/github/
https://docs.docker.com/docker-hub/builds/

**Comment by adolfintel** [comment]
It wasn't me actually; I never even used docker. See pull request #40 

If you want, feel free to add it to docker hub

**Comment by j2ghz** [comment]
I can't create an automated build, because I can't create webhooks on your repo. If I fork and add it to mine, then I have to pull your changes and it's not automated anymore.

**Comment by adolfintel** [comment]
Oh, ok. I guess I'll do it then.
I was hoping to avoid this because I don't know anything about docker; I hope I can figure out what I have to do.

**Comment by adolfintel** [comment]
Can you check if I did it correctly? It seems to build right
https://hub.docker.com/r/adolfintel/speedtest/

**Comment by j2ghz** [comment]
It works for me. Thanks 👍

**Comment by adolfintel** [comment]
Perfect :)
