### ISSUE TITLE
Unexpected low dowload speed

### ISSUE THREAD

**Issue by burevestnik1983** [adolfintel/speedtest#42]
Hello!
I have downloaded speedtest from here https://github.com/adolfintel/speedtest.git
I have apache 2.4+ PHP Version 5.4.37.
I see, that download speed is extremely low, like 0.7-0.9 Mbps.
Code from gitup were copied to server as is, no chages yet.
empty.php, garbage.php accessible, no errors in browser console, when I run test, only message:
"
Object { time_ul: 15, time_dl: 15, time_ulGraceTime: 3, time_dlGraceTime: 1.5, count_ping: 35, url_dl: "garbage.php", url_ul: "empty.php", url_ping: "empty.php", url_getIp: "getIP.php", xhr_dlMultistream: 10, ещё 6… }
"
I'm sure in my line speed. When I run http://speedtest.fdossena.com/, I get 65 Mbps download speed.

What shoud I check (change) in my Apace or Php settings?

**Comment by adolfintel** [comment]
The first thing you should check is if garbage.php is reachable. Try typing the URL of your speedtest /garbage.php and see if you get an error

**Comment by burevestnik1983** [comment]
When I try to open /garbage.php directly I see no error
It gives me 156byte binary file to download.
Respone (in firebug) is:
"
{
  "log": {
    "version": "1.1",
    "creator": {
      "name": "Firefox",
      "version": "54.0"
    },
    "browser": {
      "name": "Firefox",
      "version": "54.0"
    },
    "pages": [
      {
        "startedDateTime": "2017-06-27T16:36:52.895+03:00",
        "id": "page_2",
        "title": "Speedtest",
        "pageTimings": {
          "onContentLoad": -1,
          "onLoad": -1
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_2",
        "startedDateTime": "2017-06-27T16:36:52.895+03:00",
        "time": null,
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "http://speedtest.lan/2/garbage.php",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "speedtest.lan"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0"
            },
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
            },
            {
              "name": "Accept-Language",
              "value": "ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            }
          ],
          "cookies": [],
          "queryString": [],
          "postData": {
            "mimeType": "",
            "params": [],
            "text": ""
          },
          "headersSize": 356
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Tue, 27 Jun 2017 13:36:45 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.12 (FreeBSD) PHP/5.4.37"
            },
            {
              "name": "X-Powered-By",
              "value": "PHP/5.4.37"
            },
            {
              "name": "Content-Description",
              "value": "File Transfer"
            },
            {
              "name": "Content-Disposition",
              "value": "attachment; filename=random.dat"
            },
            {
              "name": "Content-transfer-encoding",
              "value": "binary"
            },
            {
              "name": "Cache-Control",
              "value": "no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Content-Length",
              "value": "156"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=100"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Content-Type",
              "value": "application/octet-stream"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/octet-stream",
            "size": 156,
            "encoding": "base64",
            "text": "PGJyIC8+CjxiPkZhdGFsIGVycm9yPC9iPjogIENhbGwgdG8gdW5kZWZpbmVkIGZ1bmN0aW9uIG9wZW5zc2xfcmFuZG9tX3BzZXVkb19ieXRlcygpIGluIDxiPi9vcHQvd3d3L3NwZWVkdGVzdC5sYW4vMi9nYXJiYWdlLnBocDwvYj4gb24gbGluZSA8Yj4xODwvYj48YnIgLz4K"
          },
          "redirectURL": "",
          "headersSize": 476,
          "bodySize": 156
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "send": 0,
          "wait": 0,
          "receive": 0
        },
        "serverIPAddress": "194.187.205.250",
        "connection": "80"
      }
    ]
  }
}
"

**Comment by adolfintel** [comment]
Can you give me that 156byte file?

**Comment by burevestnik1983** [comment]
I'm sorry. It's my fault. This 156 byte file contained such message:
<br />
<b>Fatal error</b>:  Call to undefined function openssl_random_pseudo_bytes() in <b>/opt/www/speedtest.lan/2/garbage.php</b> on line <b>18</b><br />

I have installed openssl support in php. In Freebsd that is php5-openssl port.
Restarted apache, and after that download speed is fine.
Maybe it's worth to add to do doc.md, that it's required to install openssl support in php

**Comment by adolfintel** [comment]
Good to know. I never tested this on BSD
