### ISSUE TITLE
Results are higher than maximum possible.

### ISSUE THREAD

**Issue by burevestnik1983** [adolfintel/speedtest#43]
I have noticed, that test result I get are higher, than can be.
My PC is in 100Mpbs port. Maximum I can get is 98 Mbps, it's phisical limit, no more.
But in this test I get 102 Mbps both download and upload - it's greater than port capability!. 
I have checked Apache and php configuration - all compression is disabled;

$ cat httpd.conf | grep defla
#LoadModule deflate_module libexec/apache24/mod_deflate.so    

$ cat httpd.conf | grep zli    - no result

in garbage.php i have directives:
<?php
// Disable Compression
@apache_setenv('no-gzip', 1);
@ini_set('zlib.output_compression', 0);
@ini_set('implicit_flush', 1);
@ini_set('output_buffering', 'Off');
@ini_set('output_handler', '');

Nevertheless, speedtest results are still above phisical capability of interface?

What should I check or change?

**Comment by burevestnik1983** [comment]
<?php
// Disable Compression
@apache_setenv('no-gzip', 1);
@ini_set('zlib.output_compression', 0);
@ini_set('implicit_flush', 1);
@ini_set('output_buffering', 'Off');
@ini_set('output_handler', '');

**Comment by burevestnik1983** [comment]
<?php
// Disable Compression
@apache_setenv('no-gzip', 1);
@ini_set('zlib.output_compression', 0);
@ini_set('implicit_flush', 1);
@ini_set('output_buffering', 'Off');
@ini_set('output_handler', '');

Nevertheless, speedtest results are still above phisical capability of interface?

What should I check or change?

**Comment by burevestnik1983** [comment]
<?php
// Disable Compression
@apache_setenv('no-gzip', 1);
@ini_set('zlib.output_compression', 0);
@ini_set('implicit_flush', 1);
@ini_set('output_buffering', 'Off');
@ini_set('output_handler', '');

Nevertheless, speedtest results are still above phisical capability of interface?

What should I check or change?

**Comment by adolfintel** [comment]
In doc.md where I mention ```overheadCompensationFactor```, that's just a rough estimate measured on my internet connection. If you're running this on a local network you might want to change it to ```1.0369```

**Comment by burevestnik1983** [comment]
Thanks a lot. That's working now. Results as expected.

**Comment by adolfintel** [comment]
No problem 👍
