### ISSUE TITLE
I want to know how to modify the full speed threshold of the chart.

### ISSUE THREAD

**Issue by aperioristo** [adolfintel/speedtest#439]
Sorry, my ability is not very good, and my English is also very poor.
I want to know how to modify the full speed threshold of the chart.
At present, as long as the speed reaches 100Mbps, it is full, and I hope to modify it to more.

**Comment by adolfintel** [comment]
The function you're looking for is called `mbpsToAmount` and it's part of the example HTML files.
Assuming you're using `example-singleServer-full.html`, here it is https://github.com/librespeed/speedtest/blob/eca7f06e217b739e2c6cb14f3f4b4da9ea9be921/example-singleServer-full.html#L46

The function takes a value in mbps in input and outputs a value between 0 and 1 that determines how full the gauge is.

The current implementation doesn't have a limit, it just increases more slowly as the speed gets higher.

Hope that helps

**Comment by imxyd-com** [comment]
> The function you're looking for is called `mbpsToAmount` and it's part of the example HTML files. Assuming you're using `example-singleServer-full.html`, here it is
> 
> https://github.com/librespeed/speedtest/blob/eca7f06e217b739e2c6cb14f3f4b4da9ea9be921/example-singleServer-full.html#L46
> 
> The function takes a value in mbps in input and outputs a value between 0 and 1 that determines how full the gauge is.
> 
> The current implementation doesn't have a limit, it just increases more slowly as the speed gets higher.
> 
> Hope that helps

Thank you, I got it! 

> The function you're looking for is called and it's part of the example HTML files. Assuming you're using , here it is `mbpsToAmount``example-singleServer-full.html`
> 
> https://github.com/librespeed/speedtest/blob/eca7f06e217b739e2c6cb14f3f4b4da9ea9be921/example-singleServer-full.html#L46
> 
> The function takes a value in mbps in input and outputs a value between 0 and 1 that determines how full the gauge is.
> 
> The current implementation doesn't have a limit, it just increases more slowly as the speed gets higher.
> 
> Hope that helps

Thank you, I got it!

**Comment by imxyd-com** [comment]
> The function you're looking for is called and it's part of the example HTML files. Assuming you're using , here it is `mbpsToAmount``example-singleServer-full.html`
> 
> https://github.com/librespeed/speedtest/blob/eca7f06e217b739e2c6cb14f3f4b4da9ea9be921/example-singleServer-full.html#L46
> 
> The function takes a value in mbps in input and outputs a value between 0 and 1 that determines how full the gauge is.
> 
> The current implementation doesn't have a limit, it just increases more slowly as the speed gets higher.
> 
> Hope that helps

Thank you, I got it!
