### ISSUE TITLE
Server without php

### ISSUE THREAD

**Issue by tayzee** [adolfintel/speedtest#45]
Hi there, 

Ive installed your project onto a server that does not have php installed. I have literally just installed it as described in the doc, without any modification.

It seems to work fine, I get test results. Does this mean that my results are not correct?

Am I required to do any of the "without php" steps?

Thanks

**Comment by tayzee** [comment]
I realized that it wasn't working properly.

I have downloaded the 7z as recommended by your doc, it's only 1mb though,
is this alright?

I also changed the getip settings to just get the ip from an API that
returns the ip.

Lastly, I'm not sure how to produce the 200 response, but it seems like
this might not even be necessary?

Thanks for the quick response.

**Comment by adolfintel** [comment]
You have to extract the .7z file, there's a 100mb file inside it.

The 200 response for the ping test can be reproduced if you simply point it to an empty file

**Comment by tayzee** [comment]
Ok cool, thanks for your response.

**Comment by adolfintel** [comment]
No problem. I'm closing the issue, but feel free to write here again if you need help

**Comment by tayzee** [comment]
Sorry, one last question.

The Main reason I'm setting this up is that we manage some servers in
Africa where we have mobile clients uploading and downloading data to these
servers. Mobile connectivity out there is very bad, a lot of the time only
2G. Given this, 100mb file for the test would be slightly overboard in this
case, it would take forever to complete the test. A file of say 1 or 2 megs
would still be sufficient in this case right?

**Comment by adolfintel** [comment]
The file will not be downloaded entirely, by default it stops after 15 seconds.

**Comment by tayzee** [comment]
Ok I see!

Thanks again.
