### ISSUE TITLE
Progress bar feature

### ISSUE THREAD

**Issue by kolosovski** [adolfintel/speedtest#47]
Hello,

First of all, thank you for the nice program.
Did you think about implementing some tiny download/upload progress bar and speed graph in the bottom?

**Comment by adolfintel** [comment]
It is certainly a good idea.
Right now I'm working on another project so I can't do it straight away. I'll leave the issue open to remind myself in the next few weeks, or if someone else wants to do it

**Comment by nakhmanson** [comment]
Hello,
Could you also add "Packet loss" value calculated from for example 100 pings?
Packet loss would allow to calculate MOS score for G711 codec. 
Thank you.

**Comment by adolfintel** [comment]
Packet loss cannot be measured over HTTP unfortunately

**Comment by Pilskalns** [comment]
Hi,

Needed to debug new setup and lurked little trough code. It should be possible to add one more parameter (i.e. `testProgress`)  to the service worker [status message](https://github.com/adolfintel/speedtest/blob/master/speedtest_worker.js#L61) without breaking existing array implementations.

Then through the code could update `testProgress` and from frontend code endless ways to display it.

**Comment by adolfintel** [comment]
@Pilskalns Yes it is possible and it is one of the features coming in the next release

**Comment by adolfintel** [comment]
I finally got around to implementing this.
It's coming in the next version, planned for next week.
