### ISSUE TITLE
NEED A MAINTAINER!

### ISSUE THREAD

**Issue by adolfintel** [adolfintel/speedtest#49]
I'm looking for someone who can help me maintain this project, at least for a couple of months.

As a maintainer you will have full access to the project, and you will have to
* Respond to requests and issues. Typically it's just people who need help setting up the speedtest on their server. 1-2 every day on average
* Implement minor changes, like adding small features or fixing bugs

I will be available to assist you, but I'll be working on a new project that will be done by the end of september.

If you'd like to help, please answer to this issue or write me at dosse91@paranoici.org

**Comment by chanstag** [comment]
I noticed you're looking for a maintainer. I'd like to offer assistance. I've been using your script for about 2 months now.

**Comment by adolfintel** [comment]
That's great :)
Can you send me an email?

**Comment by chanstag** [comment]
Yeah, it's chanstag@live.com.
