### ISSUE TITLE
I suspect that the measured values are inaccurate

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [adolfintel/speedtest#5]
I know I have 300 Megabits/second a symmetric network channel.

[This web](https://www.movistar.es/particulares/test-de-velocidad/) provides me real values:

![image](https://cloud.githubusercontent.com/assets/6008104/20621965/fc10ef12-b300-11e6-8e42-151b5a63bc85.png)

whereas [your web](http://adolfintel.com/?p=speedtest/testnew.frag) provides me unrealistic ones:

**Comment by adolfintel** [comment]
That's not an issue, my website is hosted on a cheap hosting

**Comment by DavidPerezIngeniero** [comment]
But if I test on my server with good quality Internet connection, the results are also unrealistic also:
![image](https://cloud.githubusercontent.com/assets/6008104/20622283/6717ae58-b302-11e6-9a14-ca13cfc07fa9.png)
There must be some bug....

**Comment by adolfintel** [comment]
Is there a proxy in between?
Looks like buffering and/or compression.

**Comment by DavidPerezIngeniero** [comment]
No proxy.
Maybe this data from Chrome can provide a clue:
![image](https://cloud.githubusercontent.com/assets/6008104/20622620/0c95af1e-b304-11e6-91f2-87b2afc30bbe.png)

**Comment by adolfintel** [comment]
Hmmm I'm sure there's some data compression going on there.
I have to make that data incompressible in the next version

**Comment by DavidPerezIngeniero** [comment]
Thanks, I'll check....

**Comment by DavidPerezIngeniero** [comment]
That's right. It's compressed.
![image](https://cloud.githubusercontent.com/assets/6008104/20622818/ee2b2ada-b304-11e6-8862-e9833647fcd5.png)

**Comment by DavidPerezIngeniero** [comment]
How to disable mod_gzip in Apache:

    SetEnv no-gzip 1

**Comment by DavidPerezIngeniero** [comment]
Now download speed is good.
Upload speed is still too high.

**Comment by adolfintel** [comment]
I'm working on it. The upload test sends 10mb of zeroes, so it's compressible.

**Comment by DavidPerezIngeniero** [comment]
I've discovered that the given results are in Megabytes/second, not Megabits/second.  In that case they are correct!. :-)

**Comment by adolfintel** [comment]
They should be in megabits/s, unless the guy who did example4 changed something

**Comment by adolfintel** [comment]
I made a couple of changes on the version on my site that should prevent the issue you're having.
Clear the cache and try again: [Speed Test](http://testing.adolfintel.com)

**Comment by DavidPerezIngeniero** [comment]
Thanks.  The values look like more realistic.  I have to measure in an environment whose speed I know.

I'm now in a place where speed changes:
![image](https://cloud.githubusercontent.com/assets/6008104/20667123/04365b5a-b568-11e6-8061-33b940f7c01f.png)
![image](https://cloud.githubusercontent.com/assets/6008104/20667144/15e16c8c-b568-11e6-9ff3-74ea8217c2f8.png)

**Comment by adolfintel** [comment]
The download speed may be wrong because of the hosting but the upload is still very off.
I wonder why I can't to replicate this issue on any device or network.
