### ISSUE TITLE
Chart - Latency

### ISSUE THREAD

**Issue by ric79** [adolfintel/speedtest#51]
Hello, 
first of all thanks for this beautiful tool. 

When I run the chart example, the latency chart looks very strange. It happens that I have just two points (red and green) or two lines. Is it normal?

![2017-07-14_111112](https://user-images.githubusercontent.com/6887824/28206159-31f5b132-6885-11e7-83bf-16257d03f0db.png)

**Comment by adolfintel** [comment]
It works fine here, did you change any of the settings?

**Comment by ric79** [comment]
No, but in order to have a chart a bit more cool I'm now starting it with
`w.postMessage('start {"count_ping": "500" }')`

![2017-07-14_120520](https://user-images.githubusercontent.com/6887824/28208180-c83644b6-688c-11e7-8490-bdb5bc3ffae9.png)

**Comment by adolfintel** [comment]
Fair enough. But it stilll doesn't look like it's doing 500 pings to me. Can you send me a link to your test? dosse91@paranoici.org

**Comment by ric79** [comment]
Unfortunately it is a corporate network, you can't reach it. 
However you are right. I modified in this way:

                if (status === 2 && Number(data[3]) > 0) {
                    i += 1; 
                    chart2.data.datasets[0].data.push(Number(data[3]))
                    console.log(i, Number(data[3]))

... and there are just 21 samples...

**Comment by adolfintel** [comment]
Press F12, go to network and run the test, see if there are a lot failed requests

**Comment by ric79** [comment]
I added
              `xhr[0].open('GET', settings.url_ping + url_sep(settings.url_ping) + 'r=' + Math.random() + "_" + i, true) // random string to prevent caching`

And I can see 100 doPing ... but there are 3 empty.php?r=0.606892254126236 with error "STALLED"

**Comment by adolfintel** [comment]
Hmmm maybe your server's firewall thinks that the ping test is a DDOS attempt?

**Comment by ric79** [comment]
It could be, i'm going to investigate with the networking guys. Is there a way to add a delay between doPost? maybe this can avoid the problem

**Comment by adolfintel** [comment]
At line 348 in speedtest_worker.js you can replace
```doPing();```
with
```setTimeout(doPing, 1000)```
where 1000 is a delay in milliseconds.
This way you'll only do 1 request per second. Of course you should lower count_ping to something like 10.

**Comment by ric79** [comment]
You idea causes an infinite test. However I changed to
```
 var doPing = function () {
    setTimeout( function() {
     ....
    },100) }.bind(this)
  doPing() // start first ping
}
```
and now the chart looks better (35 samples)
![2017-07-14_144916](https://user-images.githubusercontent.com/6887824/28212908-f891aa94-68a3-11e7-98a2-8b1188ee9a7a.png)

The STALLED error persists but refers to last sample of upload phase
![2017-07-14_145815](https://user-images.githubusercontent.com/6887824/28213106-ed45d0f6-68a4-11e7-8868-cfd02f290b96.png)

**Comment by adolfintel** [comment]
Ok, that should work. Still, you should investigate why your server is doing that
