### ISSUE TITLE
More info on overheadCompensationFactor

### ISSUE THREAD

**Issue by ric79** [adolfintel/speedtest#53]
Hello,
could you explain me better the value 1.13359567567567567568 (1048576/925000). How did you 
compute it?

R

**Comment by adolfintel** [comment]
925000 is 1048576 - (HTTP Overhead estimate + TCP header size + IPv4 header size + Eth header and trailer size + ADSL Overhead estimate)

I don't remember the exact values because I did that a long time ago, but it was measured on a fairly typical home internet connection

**Comment by ric79** [comment]
Ok, I hoped you could give me a pointer to a doc with this stats...

**Comment by adolfintel** [comment]
I'm sorry I really don't remember, but you can easily find the various headers on wikipedia and do the math yourself
