### ISSUE TITLE
getIP.php is not retrieving the IP address and  no jitter values are fetched!

### ISSUE THREAD

**Issue by DavidHall21** [adolfintel/speedtest#54]
Hi Adol,

I have tried testing this code in my test environment (Oracle Linux 6.9) 
it is not providing  me the  IP address of the server
Error:  Your IP: <?php echo $_SERVER['REMOTE_ADDR']
Jitter values are not populating at all.:
![tester](https://user-images.githubusercontent.com/22658296/29022308-a594ca9c-7b1d-11e7-907b-873991b4aff5.JPG)

Jitter
?>
ms

download, upload and ping test works like a charm but not the jitter value and IP option. Please advise.

**Comment by adolfintel** [comment]
It looks like PHP is not enabled, or installed

**Comment by DavidHall21** [comment]
Hey Adol,

I have the httpd already installed. Do you suggest installing the below:

yum install php-gd php-mysql

**Comment by adolfintel** [comment]
Yes, you need PHP 5.3 or newer

**Comment by adolfintel** [comment]
And openssl if not already present

**Comment by DavidHall21** [comment]
Bingo Mate!!!
it is working. However, do I need to add any parameter to make this service work every time server reboots
like an entry in  /etc/rc.local ???

**Comment by adolfintel** [comment]
The ping test is not an actual ICMP ping, so they may differ slightly. My guess in this case is that the server is taking some time to process the requests, or maybe there's a limit in how many requests it can serve. Check the server config.

**Comment by DavidHall21** [comment]
Which server configuration you are referring to I see multicast is enabled for eth3 which is the only NIC card assigned to this server host.
 grep -i multi /boot/config-3.8.13-118.19.2.el6uek.x86_64
# CONFIG_OPROFILE_EVENT_MULTIPLEX is not set
CONFIG_NEED_MULTIPLE_NODES=y
# CONFIG_CPU_IDLE_MULTIPLE_DRIVERS is not set
CONFIG_IP_MULTICAST=y
CONFIG_IP_MULTIPLE_TABLES=y
CONFIG_IP_ROUTE_MULTIPATH=y
CONFIG_IP_MROUTE_MULTIPLE_TABLES=y
CONFIG_IPV6_MULTIPLE_TABLES=y
CONFIG_IPV6_MROUTE_MULTIPLE_TABLES=y
CONFIG_NETFILTER_XT_MATCH_MULTIPORT=m
CONFIG_NET_SCH_MULTIQ=m
CONFIG_SCSI_MULTI_LUN=y
# CONFIG_MULTICORE_RAID456 is not set
# CONFIG_MD_MULTIPATH is not set
CONFIG_DM_MULTIPATH=m
CONFIG_DM_MULTIPATH_QL=m
CONFIG_DM_MULTIPATH_ST=m
CONFIG_PPP_MULTILINK=y
CONFIG_MISDN_HFCMULTI=m
CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
# Multifunction device drivers
# Multimedia core support
# Multistandard (satellite) frontends
# Multistandard (cable + terrestrial) frontends
CONFIG_HID_MULTITOUCH=m
# netstat -g
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      all-systems.mcast.net
eth3            1      all-systems.mcast.net
lo              1      ff02::1
eth3            1      ff02::202
eth3            1      ff02::1:ffb4:1383
eth3            1      ff02::1

**Comment by adolfintel** [comment]
I mean your web server (apache I assume).
Either way, I'm not an expert but I know that it works perfect with the default settings.

**Comment by DavidHall21** [comment]
Hey Adol, you have done an incredible coding mate. Really appreciate that. I am just trying to understand on which service or the default configuration file needs to be modified here. Have you tested on you system for the average respnose time from your base machine to a target server with this setup and have you verified the difference value in the ping output ??
if your base machine gives a ping response in some 300 ms then the program should also give the similar result in 350 ms...
please advice..

**Comment by adolfintel** [comment]
My best guess in these cases is the web server config, apache. Make sure there's no throttling or anything that could delay a bunch of requests. Also make sure your firewall doesn't think that this is a DDOS.

**Comment by adolfintel** [comment]
And make sure that the web server is sending Connection: keep-alive

**Comment by DavidHall21** [comment]
I have enabled the keep-aclive for the httpd service and seemingly it is giving a better response with the test. I am still performing some other checks which you  have recommended w.r.t Firewall for network level restrtictions. Will keep you updated, Thanks heaps mate...

**Comment by DavidHall21** [comment]
Hi Adol,
can we minimize the jitter values for this program?
I see higher jitter values some times. Does high jitter value impedes the over all speed test quality with this program?

**Comment by adolfintel** [comment]
It may have something to do with the fact that you've installed it on a router with extremely limited resources ;)

**Comment by adolfintel** [comment]
You should investigate the cause of this high jitter. It's unlikely to be the test itself since it's just sending a bunch of requests and seeing how long the server takes to respond.

**Comment by DavidHall21** [comment]
I will check on that. I have inserted a jpg file and it is coming fine on the web page
but is it should come right the key word "Speed test" am not sure how to do pull it right above that...

<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="referrer" content="no-referrer" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no" />
    <title> Herbalife Internal Speedtest</title>
      <img src="smilejpg"> ---------------------------------------------> this one am not sure!

**Comment by DavidHall21** [comment]
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="referrer" content="no-referrer" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no" />
    <title> Speedtest</title>
               <img src="smile.jpg"> --------->    I am not getting this page in the middle.. am not sure how to go about it...

**Comment by adolfintel** [comment]
Can you email me your code so I can see if there are any obvious mistakes?
dosse91@paranoici.org

**Comment by DavidHall21** [comment]
Mate Adol, I fixed it.  last question mate, how to I enable all check boxes for this program..

**Comment by adolfintel** [comment]
You used example7 as a base? You should have used example6 if you didn't want the checkboxes.
Since you've already made the changes, just hide the checkboxes with a display:none.

**Comment by DavidHall21** [comment]
Yes mate, I have used example 7 as base code. I tried to tweak the code with display: none but seemingly it did not for me. 
In which line of the code I need to set the his value?

  <h3>Download</h3>
                <p class="display-4 st-value"><span id="st-download"></span></p>
                <p class="lead">Mbit/s</p>
                <p><input type="checkbox" id="st-download-checkbox"></p>
            </div>
            <div class="col-lg-3 col-md-6 mb-3 st-block">
                <h3>Upload</h3>
                <p class="display-4 st-value"><span id="st-upload"></span></p>
                <p class="lead">Mbit/s</p>
                <p><input type="checkbox" id="st-upload-checkbox"></p>
            </div>
            <div class="col-lg-3 col-md-6 mb-3 st-block">
                <h3>Ping</h3>
                <p class="display-4 st-value"><span id="st-ping"></span></p>
                <p class="lead">ms</p>
                <p><input type="checkbox" id="st-ping-checkbox" checked></p>
            </div>
            <div class="col-lg-3 col-md-6 mb-3 st-block">
                <h3>Jitter</h3>
                <p class="display-4 st-value"><span id="st-jitter"></span></p>
                <p class="lead">ms</p>
            </div>

**Comment by adolfintel** [comment]
You never did web development, did you?
In the checkboxes, where it says ``input type="checkbox"`` add ``style="display:none"``, that will hide them

**Comment by adolfintel** [comment]
Also add ``checked`` to all of them, so they will all be selected

**Comment by DavidHall21** [comment]
I have fixed it. my apologies Adol. I have never done web development. I will learn it eventually.
How to I  read and understand this code from a technical prospective. I meant if I had to explain a non-technical guy how to go about it...

**Comment by adolfintel** [comment]
If you don't have experience in web development I don't recommend that you start by reading this code, since there is some relatively advanced stuff like web workers. Follow some tutorials and come back when you feel confident ;)

**Comment by DavidHall21** [comment]
sure Adol, any specific website you  strongly recommend for learning the web development?

**Comment by adolfintel** [comment]
https://www.w3schools.com/ is probably the most popular, that's how I learnt most of my HTML, CSS, and JS.

**Comment by DavidHall21** [comment]
Thank you so much Adol.
