### ISSUE TITLE
Firefox false upload speeds

### ISSUE THREAD

**Issue by deplexor** [adolfintel/speedtest#56]
Firefox (tried multiple forks with no addons) is reporting an unrealistic upload speed ~ 4,000 mbps, where it's really 20mbps. http://speedtest.fdossena.com/ reports it realistically as 20mbps, and chromium browsers work on my site as well.

Below is the default headers for my site:
`HTTP/2 200 
server: nginx/1.10.3 (Ubuntu)
date: Wed, 23 Aug 2017 12:37:44 GMT
content-type: text/html
content-length: 1316
last-modified: Wed, 23 Aug 2017 11:54:36 GMT
etag: "599d6cfc-524"
strict-transport-security: max-age=15768000; includeSubdomains; preload
x-content-type-options: nosniff
public-key-pins: pin-sha256="5xicsR/qwEJYfXChLoj5ABGYCdoIa9oCMKG7XTajeqI="; pin-sha256="bYL9lnto8Jb2RXnnbZwISleJe+cW+PHJC80YTGupOcc="; pin-sha256="sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M="; max-age=15552000;
x-xss-protection: 1; mode=block
content-security-policy: img-src *;
referrer-policy: no-referrer
x-frame-options: allow
accept-ranges: bytes
`
I'm using Let's Encrypt for TLS, with a very minimal nginx setup.

https://uif.sexy/speedtest/example1.html

**Comment by adolfintel** [comment]
Ok, there are a few things you should check, since it works on my website, it's likely just a configuration issue.
* First, try to use HTTP 1.1 instead of HTTP 2, there may be some wierd stuff in mozilla's HTTP2 implementation, and the test was never tested on HTTP2.
* Second, the target for this test is Apache. It has been reported running in nginx but I never tried it myself. Check your config, and if you can, try to install apache and see if you get the same issue
* Last, is there a proxy, VPN or similar between you and your server?

**Comment by deplexor** [comment]
Disabling HTTP2 seemed to fix it. It's just strange Mozilla's implementations for HTTP2 would cause issues but Chromium's wouldn't. Do you know of any ways around it?

**Comment by adolfintel** [comment]
HTTP 2 is still a very new technology, I'm sure it's just a bug with XHR and HTTP2 in firefox (probably firing progress events too soon), they'll fix it.
At the moment I would suggest that you turn off HTTP 2, at least for the speedtest.

**Comment by tzwjkl** [comment]
I also encountered some problems in the upload test part using the h2 protocol (the problem disappeared when I disabled h2 in nginx, so I think this is the reason for h2), but I was using Chrome instead of Firefox.

**Comment by adolfintel** [comment]
@tzwjkl can you give me a link to your test? I use firefox as my main browser

**Comment by tzwjkl** [comment]
> @tzwjkl can you give me a link to your test? I use firefox as my main browser
Ok, it's:
[speed.rainbowl.tk](https://speed.rainbowl.tk/)
And I enabled h2 now.

**Comment by tzwjkl** [comment]
> @tzwjkl can you give me a link to your test? I use firefox as my main browser

I apologize for not having searched for solutions and providing detailed information before.
I add `client_max_body_size 100M;` in my nginx configruation and the problem (just HTTP 413 error) is gone as well.
But I am still confused about why the error only occurred in http2

**Comment by Hoerli1337** [comment]
I have exactly the same problems.
With Firefox I only get a maximum of 75MBit/s upload.
Tested with Firefox (PC + Android), Firefox Developer and Waterfox.
With Chrom(ium) I can measure my whole 170Mbit/s.

Whether I use HTTP1.1 or HTTP2 does not matter.
client_max_body_size times set to 0, 200MB or 400MB - same results.
I have also played with the number of connections and packet size, but it does not get better.
It does not go more than 75MBit/s.
The output itself is correct, because in fact no more than 75MBit/s are going over the network.
The ping and download, however, is measured correctly.

I don't know if you have to optimize php-fpm or nginx in order to get correct measurements with Firefox.

**Comment by adolfintel** [comment]
@Hoerli1337 Can you see if the issue persists with apache?

**Comment by Hoerli1337** [comment]
I just installed a test server with Apache.
Here are the results of my tests:

**Apache2 + php7.4 + http1.1**
Download: 440Mbit/s
Upload: 170Mbit/s
=> All is well

**Apache2 + php7.4 + http2**
Download: 440MBit/s
Upload: 105Mbps
=> 70Mbit/s loss in upload

**nginx + php7.4 + http1.1**
download: 440MBit/s
Upload: 75Mbit/s
=> 100Mbit/s loss in upload

**nginx + php7.4 + http2**
Download: 440MBit/s
Upload: 75Mbit/s
=> 100Mbit/s loss in upload

Using http2 with Apache slows down the upload bandwidth enormously. nginx doesn't care, I don't get good results.
With Chrom(ium) http2 works fine with apache2 and nginx.
It seems to be a Firefox problem, but it would be nice if we could solve it :)

**Comment by adolfintel** [comment]
I'm still unable to replicate this, on my machine firefox reaches several gbps before being bottlenecked. Could it be a network issue? What's between you and the server?

**Comment by Hoerli1337** [comment]
That's odd.
There's actually nothing wrong between me and my test servers.
I can even exchange data via SSH with fullspeed.
No packet loss, no high ping, all wonderful.
**PC** <- 10GBit/s RJ45 -> **Switch** <- 1Gbit/s -> **Router** <- Fiber Optics -> **ISP**

**Comment by Hoerli1337** [comment]
Okay, I think that's probably just a problem with my computer now.
I just don't know if it's a Firefox plugin or the system itself.
With my notebook and a LAN connection, I can test my full line as usual and there I have the same AddOns in Firefox.

I have my nginx configuration here again, maybe someone has a good tip.
____________________________________________
server {
    listen 80;
    listen [::]:80;
    access_log off;
    # access_log  /var/log/nginx/speedtest.access.log;
    error_log   /var/log/nginx/speedtest.error.log crit;
    server_name speedtest.domain.de;
    # enforce https
    return 301 https://$server_name$request_uri;
}

server {

        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        access_log off;
                # access_log  /var/log/nginx/speedtest.access.log;
        error_log   /var/log/nginx/speedtest.error.log crit;
        server_name speedtest.domain.de;
        ssl_certificate /etc/letsencrypt/live/speedtest/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/speedtest/privkey.pem; # managed by Certbot

        root /var/www/speedtest;

	add_header 'Access-Control-Allow-Origin' '';

        index index.php index.html index.htm;

        client_max_body_size 200M;

        location / {
           try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
           include snippets/fastcgi-php.conf;
           fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           include fastcgi_params;
        }
}
