### ISSUE TITLE
Test Queue Feature

### ISSUE THREAD

**Issue by LordMrcS** [adolfintel/speedtest#57]
Is it possible to set up a feature to limit simultaneous tests? Setting up a queue or something like this..

Thanks in advance! Your tool is awesome!

**Comment by adolfintel** [comment]
Server side or client side?

**Comment by adolfintel** [comment]
I don't think there's any reliable way to do this.
Client side, you can only limit tests in one page, which makes no sense
Server side, there's no reliable way of knowing if a user is still connected or not. You could start a session when the page is loaded, but then when does the session end? If the user closes the browser or if it crashes, you have to wait several hours or even days for the session to expire.
