### ISSUE TITLE
about ping 

### ISSUE THREAD

**Issue by trips1990** [adolfintel/speedtest#64]
Thanks for the nice tool. 
I am getting ping as 320ms from speedtest tool but when i run ping command i see the value 153ms.

Can you guide me what needs to be checked ?
Thanks again.

**Comment by adolfintel** [comment]
Since that's roughly double the actual ping, I'm 90% sure that your server is not sending Connection: keep-alive.
I'll close the issue for the moment but feel free to write here and I'll answer
