### ISSUE TITLE
1Gbps Ethernet link testing out over 1Gbps (huh?)

### ISSUE THREAD

**Issue by BeardedGaijin** [adolfintel/speedtest#65]
Found your speedtest tool and was very happy seeing as miniookla has been taken down. I have a home gateway with 1Gbps eth ports and two Mac Book Pros each with a 1Gbps Thunderbolt/Ethernet dongles. I am running OSX Sierra on both and they have default network settings (ie MTU = 1500). Speedtest server runs on one and the other runs the speedtest client in Chrome.

When I use the text based examples my 1Gbps link is always reporting more than 1Gbps (like 1015Mbps). When I test the same connection with iperf (command line) I consistently get 940Mbps (TCP). Possible there is some type of rounding error in the speedtest calculations?

Also, when I use the XY graph example I notice that near the end of the test the speed starts to drop down to around 800Mbps on the download but the upload stays right around 1Gbps (which again is a tad high but at least it stays consistent). Perhaps this is due to some apache/php configuration? 

Both seem odd which is why I opened this issue. I have a screen shot of each. 

Thanks,

-wb
<img width="1156" alt="1gbps_eth_lan - graph based" src="https://user-images.githubusercontent.com/31901160/30343884-070c6ee4-97cd-11e7-8e7e-b985ceabf8b6.png">
<img width="1274" alt="1gbps_eth_lan - text based" src="https://user-images.githubusercontent.com/31901160/30343883-070a2e54-97cd-11e7-90ab-49c588907a9f.png">

**Comment by adolfintel** [comment]
It's because it's calibrated to compensate the overhead of HTTP+TCP+ETH+ADSL.
See the ``overheadCompensationFactor`` in the documentation.

**Comment by BeardedGaijin** [comment]
Thanks.

__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME

**Comment by adolfintel** [comment]
I'm here if you need help changing it

**Comment by BeardedGaijin** [comment]
Just reading the docs… what would you recommend for local network… 1Gbps Ethernet testing? I set it to 1 to ignore overheads and still getting over 1Gbps…. And now my graph drops off drastically….

[cid:image001.png@01D32BE0.957221F0]



__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME

**Comment by adolfintel** [comment]
I think about 1.03 should be fine.
I don't see your image though.
Also, consider that gigabit is really fast and an HTTP server may get overloaded.

**Comment by BeardedGaijin** [comment]
I think that explains the graph dropping off at the end. I can try tweaking apache. Let me try 1.03.

And here is a snap of the example6.html.

[cid:image001.png@01D32BE1.609B9000]

If you don’t get it then git is stripping it out.

-wb



__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME

**Comment by adolfintel** [comment]
That's the chart library being shit and slow, makes the browser lag so the reported speed is wrong. Sigh...

**Comment by BeardedGaijin** [comment]
Am I to be changing speedtest_worker.js? Doesn’t seem my changes are taking effect… do I need to clear my browser cache? Or restart apache? Wouldn’t think I would need to as this is all just loaded content… but I am no code expert.

__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME

**Comment by adolfintel** [comment]
You edited the example, right? Can you copy the line that starts the test?

**Comment by BeardedGaijin** [comment]
Sorry… not following… I edited the example html but just to add a graphic and change a title… no code. I have been editing the overheadCompensationFactor value in speedtest_worker.js and then loading the page from my client laptop. Am I missing something?

__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME

**Comment by BeardedGaijin** [comment]
Federico,

Sorry… I am not a software developer… took a bit more reading and reviewing the source to understand. Thanks for your patience. I was making changes to the .js file but didn’t realize that I need to uglify it. =) Once I got node.js installed (like I said not a developer much past some vi-make-makeinstall back in the day) and got uglifyjs on my system I was able to update my speedtest_worker.min.js…. now I am seeing the changes I made in my js file show when I run my speed tests.

I was able to update my overhead value and set the test time to 5 seconds which is sufficient for what I am doing.

Last note… I just opened a git account and not sure if you would want this but for OSX users the uglify command line is a tad different.

sh-3.2# uglifyjs --verbose -c --ie8 speedtest_worker.js > speedtest_worker.min.js
WARN: Collapsing xhr [speedtest_worker.js:141,2]
WARN: Collapsing speed [speedtest_worker.js:220,19]
WARN: Collapsing speed [speedtest_worker.js:337,19]
WARN: Collapsing i [speedtest_worker.js:397,12]
WARN: Collapsing xhr [speedtest_worker.js:410,2]
sh-3.2#

Thanks for a great tool!

-wb

__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME

**Comment by BeardedGaijin** [comment]
Also a browser refresh was required as well… I guess the min.js file was cached.

Thanks again.

-wb

__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME


From: Will Bober <Will.Bober@technicolor.com>
Date: Tuesday, September 12, 2017 at 6:56 PM
To: adolfintel/speedtest <reply@reply.github.com>, adolfintel/speedtest <speedtest@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [adolfintel/speedtest] 1Gbps Ethernet link testing out over 1Gbps (huh?) (#65)

Federico,

Sorry… I am not a software developer… took a bit more reading and reviewing the source to understand. Thanks for your patience. I was making changes to the .js file but didn’t realize that I need to uglify it. =) Once I got node.js installed (like I said not a developer much past some vi-make-makeinstall back in the day) and got uglifyjs on my system I was able to update my speedtest_worker.min.js…. now I am seeing the changes I made in my js file show when I run my speed tests.

I was able to update my overhead value and set the test time to 5 seconds which is sufficient for what I am doing.

Last note… I just opened a git account and not sure if you would want this but for OSX users the uglify command line is a tad different.

sh-3.2# uglifyjs --verbose -c --ie8 speedtest_worker.js > speedtest_worker.min.js
WARN: Collapsing xhr [speedtest_worker.js:141,2]
WARN: Collapsing speed [speedtest_worker.js:220,19]
WARN: Collapsing speed [speedtest_worker.js:337,19]
WARN: Collapsing i [speedtest_worker.js:397,12]
WARN: Collapsing xhr [speedtest_worker.js:410,2]
sh-3.2#

Thanks for a great tool!

-wb

__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME

**Comment by adolfintel** [comment]
Sorry for the late answer but it was night here.
You didn't have to go though all that, the speedtest can take custom parameters. You could just have edited the example and replaced
w.postMessage('start')
With
w.postMessage('start {"overheadCompensationFactor":"1.03"}')

**Comment by BeardedGaijin** [comment]
Haha… well.. yes if I was a coder… I was wondering how to pass parameters but I got it to do what I needed. I took Basic and Fortran in high school but that was over 30 years ago. =)

Now it’s late here (Atlanta, GA).

Thx again and nite.

-wb

__________________________
Will Bober
Technical Marketing Engineer
mobile +1 770 378 8745
email will.bober@technicolor.com

TECHNICOLOR CONNECTED HOME
