### ISSUE TITLE
Store test details in file

### ISSUE THREAD

**Issue by marcus-adams** [adolfintel/speedtest#66]
it would be good if the results were also saved to a csv file or something like that along with ip, address, browser,os info etc.
an enhancement on that would be to pass simple metadata like http:/speedtest/?email=me@me.org so hat would also save the email against that test

**Comment by adolfintel** [comment]
You could modify telemetry.php to store in a file instead of a database, and add an email field if you want.
Right now I'm working on another project so I don't really have time to add new features, just bug fixes.
