### ISSUE TITLE
Windows 10 identify speedtest_worker.js as a Trojan:JS/Jorv.A!cl

### ISSUE THREAD

**Issue by kibeb** [adolfintel/speedtest#69]
FYI, current version Windows 10 with fully updated Windows Defender identify speedtest_worker.js as containing a Trojan:JS/Jorv.A!cl trojan. The file is then quarantined and deleted from the original location.

**Comment by adolfintel** [comment]
There is nothing I can do about false positives in Windows Defender. Just whitelist it and it will probably report it to microsoft automatically
