### ISSUE TITLE
Static hosting nginx wiki

### ISSUE THREAD

**Issue by Pilskalns** [adolfintel/speedtest#72]
Hi @adolfintel,

For my needs, I wanted speed test without a backend (PHP, Node or whatever), just plain static `nginx`. I can share configs, how to achieve it - upload, download works like a charm, but no saving of results, of course.

Should I contribute to the main `readme.md` + `example.html` using it?

**Comment by adolfintel** [comment]
Hi,
you can write the config here and I'll put a link in readme.md and doc.md, or you can add a section in doc.md and send a PR, whichever you prefer.
