### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by seanvree** [adolfintel/speedtest#76]
First,

THANKS for this. So dope!

Second, yeah, dark theme maybe?

I know I can edit all the .css and what not, but just a thought.

Cheers!

**Comment by adolfintel** [comment]
Those are just examples. They're here so that you can copy the code and understand how to use the worker. It's not really that important, but if you want you can change the CSS of one of the examples and send a PR.

**Comment by seanvree** [comment]
@adolfintel  yes, I understand that.  

I was just thinking a "dark" themed example would be nice. 

I'll put something together and make a PR. 

THX
