### ISSUE TITLE
Question[not an issue] how to replace the txt starting

### ISSUE THREAD

**Issue by mydiyhobby** [adolfintel/speedtest#77]
hi i wanted to replace the txt "Starting" with an image " loading gif file " how can i do it please..?

` download.textContent = (status==1&&data[1]==0)?"Starting":data[1]
  upload.textContent = (status==3&&data[2]==0)?"Starting":data[2]`

your help is appreciated... thank you

**Comment by adolfintel** [comment]
Easiest way is this:
* In each of the areas, put an img with your gif, give it an id like loadDl, loadUl, etc.
* Give them a CSS classname like `hidden` and write some CSS that hides elements of that class
* In the code instead of the string `starting`, change the className of those items from `hidden` to empty string, depending on the value of `status`

Hope this helps

**Comment by mydiyhobby** [comment]
Please, Im sorry if this is wrong or if this is correct please..let me know, im new in this and i wanted to learn. (Student) :)
 
download.textContent = (status==1&&data[1]==0)?"Starting":data[1]

instead, like this..

download.textContent = (status==1&&data[1]==0)?= document.getElementById("loadDl"):data[1]

<style>
#loaDI {
display:hidden; 
background-image: url("loading.gif");
}
</style>

**Comment by adolfintel** [comment]
Probably more like this:
``
<style type="text/css">
img.hidden{
display:none;
}
</style>
``
Inside the various areas for download, upload, etc. you add 
``
<img class="hidden" src="loading.gif" id="loadDl" />
``
Where there is the update code:
``
if(status==1){
if(data[1]==0) document.getElementById("loadDl").className=""; else download.textContent=data[1];
}
``
and so on for all statuses and areas.

Hope that's clearer now

**Comment by mydiyhobby** [comment]
or this,
`
            <div class="col-lg-3 col-md-6 mb-3 st-block">
                <h3>Download</h3>
                <p class="display-4 st-value"><span id="st-download"></span></p>
                <p class="lead">Mbit/s</p>
                <p><input type="checkbox" id="st-download-checkbox"></p>
            </div>
`
instead,
`
            <div class="col-lg-3 col-md-6 mb-3 st-block">
                <h3>Download</h3>

<p class="display-4 st-value">
<div class="loadDI"></div>
<span id="st-download"></span>
</p>
                <p class="lead">Mbit/s</p>
                <p><input type="checkbox" id="st-download-checkbox"></p>
            </div>
<style>
.loadDI{
display: hidden;
background: url(loading.gif);
}
</style>
`

**Comment by adolfintel** [comment]
It's a bit messy. I suggest you use an img. That div is empty and there is no size specified in the CSS, it will not be displayed.

**Comment by adolfintel** [comment]
Also, if you copy code here, put 3 backticks before it and 3 backticks after, otherwise it will be parsed as HTML.

**Comment by adolfintel** [comment]
backtick: `

**Comment by mydiyhobby** [comment]
ok so its should be:
`
<style type="text/css">
 img.hidden { 
    display:none;
     background: url("images/loading.gif");
 } 
</style>

if(data[1]==0) document.getElementById("loadDl").className="hidden"; else download.textContent=data[1];
if (data[2]==0)document.getElementById("loadDl").className="hidden"; else download.textContent=data[2];
}
`

The original Code is:
`                download.textContent = (status==1&&data[1]==0)?"Starting":data[1]
                upload.textContent = (status==3&&data[2]==0)?"Starting":data[2]
                ping.textContent = data[3]
                ip.textContent = data[4]
                jitter.textContent = data[5]`

**Comment by adolfintel** [comment]
It's quicker if I just do it and show you. I will do it by the end of tomorrow. You're editing example8, right?

**Comment by mydiyhobby** [comment]
example: 7 :)
really sorry... im just learning...i know its a pain...

**Comment by adolfintel** [comment]
Here it is
[example.zip](https://github.com/adolfintel/speedtest/files/1400804/example.zip)

**Comment by mydiyhobby** [comment]
Thanks... im going to try this... and let you know the out come :)

**Comment by mydiyhobby** [comment]
Hi now after i use...the example code you provided...only download is working....the IP, Upload, Ping, Jitters are all not working...

**Comment by adolfintel** [comment]
It works here.
Try clearing your browser's cache

**Comment by mydiyhobby** [comment]
thank you..yeah it thus...
