### ISSUE TITLE
Ping count is Different from ookla speed test

### ISSUE THREAD

**Issue by mydiyhobby** [adolfintel/speedtest#78]
Hi,
I  compare the speed, upload are the same with eg: ookla and our local internet service provider speedtest tool here. However the Ping is like 300ms higher than ookla and our local internet service provider speedtest tool http://speedtest.du.ae/ ...!

Is there something that requires adjustment or something? Thanks

**Comment by mydiyhobby** [comment]
http://speedtest.du.ae/
Download Speed: 34.478 mps 
Upload Speed: 806 kbps 
Latency: 4 ms
Jitter: 3 ms

**From Adolffintel  speedtest**
Download: 32.74Mbit/s
Upload: 0.88Mbit/s
Ping: 384.57ms
Jitter: 105.70ms

**Comment by adolfintel** [comment]
The only thing that you need to make sure of is that your server is sending the Connection: keep-alive header. Other than this, Ookla probably has better servers than you and I, don't you think?

P.S.: As I said in #75 READ THIS BEFORE YOU OPEN AN ISSUE: please _DO NOT_ open issues for troubleshooting. Contact me directly, it's quicker. Issues are for bugs.

**Comment by mydiyhobby** [comment]
Ok...
