### ISSUE TITLE
IE 11 - only see heading "SPEED TEST", nothing else

### ISSUE THREAD

**Issue by quintingsnj** [adolfintel/speedtest#79]
I don't know if these are issues, or mis-config on my part, but here is my config.

Server 2012, IIS7, PHP5. I have several other PHP/MySQL sites running on this server, so I know PHP is configured properly. Client is Win10, IE11

In Chrome, and Edge it works (with one issue - will open new issue for that one), in IE11 (docs say IE11 is supported), it does not work. Just get header "Speed Test", nothing else on page.

If this isn't a bug, a point in the right direction would be appreciated.

Thanks.

**Comment by adolfintel** [comment]
The test is compatible with IE11, I check every time I change something.
Which example did you use as a base? That's probably the issue

**Comment by quintingsnj** [comment]
I tried every example that was included. All produce the same (or similar) results.

Thanks

**Comment by adolfintel** [comment]
That's very strange. Can you open this on your IE11? http://speedtest.fdossena.com

**Comment by quintingsnj** [comment]
Hmmm, that does work - and I assume is same version as I downloaded from github yesterday....

**Comment by adolfintel** [comment]
Yes, it's the same code.
IE11 has some security settings which may be interfering. Check your zone, make sure it allows running javascript

**Comment by adolfintel** [comment]
And if you can, give me the URL to your test so I can check with IE11 too

**Comment by quintingsnj** [comment]
URL is internal to our network. Planning to use this to test some speed issues over our VPN...in any case, yes, java scripting is enabled. Both "allow active scripts" and "scripting of java applets" are enabled on all zones on my machine.

Thanks

**Comment by adolfintel** [comment]
I'm talking about Javascript, not Java applets.
Which security zone is displayed when you are on the speedtest page?

**Comment by quintingsnj** [comment]
It's in the intranet zone. Where do I find the setting for Javascript?

**Comment by quintingsnj** [comment]
From what I understand, the setting under security settings for "active scripting" is supposed to apply to java scripting...and it is enabled in intranet zone (as well as all other zones).

Thanks

**Comment by adolfintel** [comment]
Under Internet Options > Security, make sure your Local intranet settings aren't too high. By default IE11 has it set to Medium-low; higher settings may disable it. Reset the settings if you're in doubt.

**Comment by adolfintel** [comment]
So JS is enabled but it can't even start the script?
Press F12 and see if there are any errors in the console.

**Comment by quintingsnj** [comment]
HA! My browser was set to behave like IE7....fixed it.  Thanks for your help, pointed me in the right direction :)

**Comment by quintingsnj** [comment]
Looks like a network wide setting as well - I will have to figure out which GPO is doing that :) again, much thanks!

**Comment by adolfintel** [comment]
Perfect 👍

**Comment by quintingsnj** [comment]
I hope it's OK to continue in this thread....OK, while IE11 now loads the page properly, it doesn't do the test. When you press START, everything stays at 0. Pressing abort does not abort either.  Any ideas on that one? Can't see anything out of the ordinary when looking at the F12 pane...

thanks.

**Comment by adolfintel** [comment]
Can you see in the network tab if it loaded speedtest_worker.min.js correctly?

**Comment by adolfintel** [comment]
Oh, by the way, is it example4?

**Comment by quintingsnj** [comment]
Oh, I am getting these in the "script" tab: SCRIPT438: Object doesn't support property or method 'log2' 
speedtest, line 174 character 13

Yes, speedtest_worker.min.js loads in the network tab. The garbage file is sitting at pending. Not sure how I missed this when I first looked at the F12 stuff.

And yes, Example4

**Comment by adolfintel** [comment]
Yes, that's the library that draws those gauges, they broke IE11 compatibility some time ago. I will remove that example in the next version. Use example6 insteam.

**Comment by quintingsnj** [comment]
They all do the same thing when I change the garbage.php to a non-php file...

**Comment by adolfintel** [comment]
Man what the hell is up with that client? 😆 
If you see the pending requests to the garbage file, the test is running. Can you confirm that?

**Comment by quintingsnj** [comment]
Also, I don't see the option for garbage.php in example6.

Thanks

**Comment by adolfintel** [comment]
You have to add it, 
```postMessage('start {"url_dl":"garbage.dat"}')```

**Comment by adolfintel** [comment]
There are a lot of settings that you can pass to the worker, they're all in doc.md. You pass them as a JSON string

**Comment by quintingsnj** [comment]
OK, got example 6 working in Chrome, but in IE, just says starting. Does not fill in IP address. Loads speedtest_worker.min.js and the getip.php and nothing after that. nothing in the debugger tab....

Thanks again for your help...if this doesn't work, I'm ready to give up :)


Q

**Comment by adolfintel** [comment]
Can you give me some screenshots? And the code? Zip everything and post it here, I want to make sure it's fine

**Comment by adolfintel** [comment]
I copied it on my server and it works just fine in IE11 so I don't think it's configured wrong.

![2017-10-24 21_10_49-federico 40fdossena com ftp fdossena com - filezilla](https://user-images.githubusercontent.com/16307689/31963149-11300044-b900-11e7-99e9-ed36d73145c6.png)

**Comment by adolfintel** [comment]
Is it possible that IE11 has some issues with the same origin policy because of the name of your domain though now that I look at it. Can you try accessing it directly with the IP address?

**Comment by quintingsnj** [comment]
Hmmm, that does work.....weird. I'm happy with that...will just make a link on our intranet page to it...

Q

**Comment by adolfintel** [comment]
Old IE had some issues with the same origin policy. Same thing causes problems with HTTPS, as mentioned in the documentation.
I'm sorry you had so much trouble

**Comment by quintingsnj** [comment]
No problem, I don't think it was your fault. Program looks really nice, and a great (actually better) replacement for speetest mini which they stopped providing...so thanks so much!

Q

**Comment by adolfintel** [comment]
You're welcome!
Make a donation if you want 😉

**Comment by quintingsnj** [comment]
I'll ask my boss, and if not, I may well do that personally for you :)

Have a great day!
