### ISSUE TITLE
speedtest skips download testing?

### ISSUE THREAD

**Issue by bcacbe** [adolfintel/speedtest#8]
I have the speedtest setup at the following URL, but the download speed test portion is skipped. Any idea how to fix?

http://69.42.51.25/speedtest/example4.html

**Comment by adolfintel** [comment]
Your links works perfectly.
What browser are you using?

**Comment by bcacbe** [comment]
It looks like there was some problem with the PHP script causing a 500 error. I had to change a line in the code to fix it. Seems to work ok now.

**Comment by bcacbe** [comment]
I changed line 18 to `$data=rand(1048576,false);` in garbage.php

**Comment by adolfintel** [comment]
I had to make a similar change this morning (See issue #7).
rand(1048576,false) how the rand function is supposed to be used though. See this https://secure.php.net/manual/en/function.rand.php
It generates a SINGLE number, while the old function generated 1MByte of random data.
It may work anyway but you're writing 4 bytes at a time of very compressible data. This causes high CPU overhead, and may cause incorrect results.

**Comment by bcacbe** [comment]
Okay, i just found alternative code online trying to fix it. I have uploaded your fix now. Thanks.
