### ISSUE TITLE
Download Speed Reporting Wrong

### ISSUE THREAD

**Issue by quintingsnj** [adolfintel/speedtest#80]
I don't know if these are issues, or mis-config on my part, but here is my config.

Server 2012, IIS7, PHP5. I have several other PHP/MySQL sites running on this server, so I know PHP is configured properly. Client is Win10, Google Chrome/Edge.

I get 2.16MB reporting for download on any workstation, in either Chrome or Edge browsers. This is not correct, as it should be higher than 100.  I have access to both garbage.php and empty.php. One thing of note, is that direct access to garbage.php (http://domain.com/speedtest/garbage.php) generates a 500 - internal server error (not sure what it is supposed to do if run by itself - maybe that is normal), and empty.php generates a blank page.

Any help with figuring this out would be appreciated.

Thanks.

**Comment by adolfintel** [comment]
Not a bug.
There is a configuration problem, most likely you don't have OpenSSL. If you can check the server log I can help you troubleshoot it

**Comment by adolfintel** [comment]
You can verify that by runinng this PHP script
```
echo OPENSSL_VERSION_NUMBER;
```
If OpenSSL is properly installed you'll see the version number.

If you don't need OpenSSL and don't want to install it, the speedtest can be configured to use a large file instead of garbage.php, see doc.md for the details.

**Comment by quintingsnj** [comment]
[u_ex171024.log](https://github.com/adolfintel/speedtest/files/1411559/u_ex171024.log)

Log file attached. Will run the PHP test you suggested.....and I did notice that, but didn't want to change that just yet. If I can't get this working, will try the large file method instead.

Thanks!

**Comment by adolfintel** [comment]
That's just an access log, I need the log from PHP to see the error

**Comment by quintingsnj** [comment]
If openssl is not properly installed, what happens? I get a 500 - internal server error.

Also, tried replacing garbage.php with garbage.7z (from your site), and changed code to read: w.postMessage('start {"time_ul": "10", "time_dl": "10", "count_ping": "50", "url_dl": "garbage.7z", "url_ul": "empty.php", "url_ping": "empty.php", "url_getIp": "getIP.php"}')

I still get same download results.

**Comment by adolfintel** [comment]
You have to extract garbage.7z, otherwise it's just a small file, and make sure you don't get errors from that too.

**Comment by adolfintel** [comment]
Very good :)
