### ISSUE TITLE
feature requests: optional notes entry

### ISSUE THREAD

**Issue by gessel** [adolfintel/speedtest#81]
Telemetry is really cool - thanks!  It would be helpful, at least in my instance, to have a notes field that could be populated at test time.  This would make the collected telemetry data a lot more useful in at least my use case.

Thanks for a great piece of code.

**Comment by adolfintel** [comment]
It could be added, but it seems very specific for your use case so maybe a fork would be better? You pass the note to the worker when it starts and it simply appends it to the telemetry.

**Comment by gessel** [comment]
I note there's a "log" column in the table - unused?  Perhaps just write to that and create a new example9_telemetry.html

My use case is a large LAN where our field tests might be carried out using a laptop here or there - they'll generally get the same IP regardless of where they connect, so that value isn't so useful for keeping records.  The tester could just record the location.




-------- Original Message --------
Subject: Re: [adolfintel/speedtest] feature requests: optional notes entry (#81)

**Comment by adolfintel** [comment]
The log is not unused, it writes a log when telemetry is set to full (default is basic so it's empty)
My idea was this:
* Create an index.html for your specific use case, starting from the telemetry example
* In speedtest_worker.js, add an empty ```note``` field, and modify the telemetry function to send ```settings.note+" "+log```
* In your index.html, the note is passed to the worker when it is started, like this: 
```
s={note: /*get your note here*/ };
w.postMessage('start '+JSON.stringify(s))
```

The test will parse the new setting automatically and append it to the log when it sends the telemetry.
I can help you make those changes if you fail.

**Comment by gessel** [comment]
have you done any testing on 10G networks?  Is there a software limit?  
We got a max of 1.78 G on a 10 G links. 

On 2017-10-24 19:49, Federico Dossena wrote:

> It could be added, but it seems very specific for your use case so maybe a fork would be better? You pass the note to the worker when it starts and it simply appends it to the telemetry. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/adolfintel/speedtest/issues/81#issuecomment-339056722
[2]

**Comment by adolfintel** [comment]
In theory it works, and it's been confirmed working by some users. In practice it depends on your machines.
Server side it has to be fast enough, of course.
Client side however, the script can only send XHR requests as fast as the CPU allows, if you see high CPU usage, the test is bottlenecked by javascript.
