### ISSUE TITLE
Re-load issue on IE11

### ISSUE THREAD

**Issue by kenliele** [adolfintel/speedtest#84]
I tried both example html or http://speedtest.fdossena.com/ in IE11
It is failed to run by step below to reproduce
1. "Start" to run the speed test
2. Refresh the page
3. Click "Start" again, it is unable to run.
In debugger, it shown HTML1300 and DOM7011 (https://msdn.microsoft.com/library/dn265017(v=vs.85).aspx)

How to resolve

**Comment by adolfintel** [comment]
I'm unable to reproduce this, You sure you didn't accidentally hit the compatibility mode switch?

**Comment by kenliele** [comment]
I am sure I am not in compatibility of IE11
The key is step2. Refresh the page on same window, or just go to URL, press "Enter" to re-load
And another issue I found is : after I tried run several time of test by "start" in IE11, it will be freeze also.
Or just simply set "garbagePhp_chunkSize" to "100", it will first wait long time to show Download rate, on 2nd or 3rd run, it will be freeze.

Is it due to IE11 memory limitation or caching limit??

**Comment by adolfintel** [comment]
There might be a memory leak in IE11 then, let me check.
If that's the case, there is nothing I can do but it's good to know.

**Comment by adolfintel** [comment]
Nope, still can't reproduce after 6 runs. Memory is deallocated correctly when the page is refreshed, but not when you do multiple runs without reloading the page (so many consecutive runs may freeze or crash IE).

**Comment by kenliele** [comment]
Try in other browser, only IE11 have the symptom mentioned.
I will try on other PC with IE11 tomorrow, to see if similar issue.
Thanks

**Comment by adolfintel** [comment]
I have a IE11 testing VM

**Comment by kenliele** [comment]
I am running in IE11 in Windows 10, 64bit

**Comment by kenliele** [comment]
To report as I try on 4 PC, result of 2 issues mentioned as below for your info,
**Issue 1 :  About freeze after reload on same IE11 window tab**
2 PC having no problem, which are windows 7, with IE11 (version 11.0.9600.18617)
2 PC having problem as described, which are windows 10, with IE11 (version 11.674.15063.0)
More symptoms as below
1. I tried to track on those IE11 (version 11.674.15063.0), the postMessage not listensing/functioning after refresh/reload the page in same tab, whatever I wait time to reload
2. Without closing IE11, reload in new tab
a. after running 1st time, then open new tab instantly and load again, Result : postMessage not work
b. after running 1st time, then wait ~30-1 min, then open new tab and load again, Result : postMessage working

**Issue 2 :  About freeze after several size of download/upload tested on IE11 **
All 4 PCs having same result, and I monitor memory changes in window task manager,
I believe it keep add to memory without release memory per package like Edge/Firefox/Chrome behaved
Just to see if there is any can do to release memory in IE11 on coding

**Comment by adolfintel** [comment]
Ok, thanks for the info.
I didn't expect them to introduce new bugs in IE11.
Just for curiosity, is the test hosted on some unusual URL? Like http://abc/speedtest ?

**Comment by adolfintel** [comment]
Also, the error code seems to have something to do with caching.
Can you try editing empty.php and gargabe.php and removing these lines from both?
```
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
```

**Comment by kenliele** [comment]
those result I test is running on localhost of PC, 
also you can try on http://www.atoms-muse.com/site/speed_test.php

**Comment by adolfintel** [comment]
Did you try removing those lines I mentioned?

**Comment by kenliele** [comment]
I tried to remove those 3 lines on both garbage.php & empty.php
But it looks nothing different.
What you assume it will affect on output/result??
