### ISSUE TITLE
Why not use UTF-8 encoding ?

### ISSUE THREAD

**Issue by saldru** [adolfintel/speedtest#87]
Hi,

I want to know why you use **Windows-1252** encoding charset instead of the universal **UTF-8** encoding charset ?

In my own speedtest server, I replaced your charset by UTF-8 and there are no problem.
So maybe change for recommandations of UTF-8 or if you have a reason, can you explain me. :)

Saldru

**Comment by adolfintel** [comment]
Because I'm an idiot and I forgot to put the character encoding header. Well spotted. I'll fix it in the next version, coming in a few days

**Comment by adolfintel** [comment]
This is only relevant for the HTML files and getIp.php though. empty.php and telemetry.php don't output anything, and garbage.php outputs a binary blob.
