### ISSUE TITLE
Download Rating

### ISSUE THREAD

**Issue by kenliele** [adolfintel/speedtest#88]
I had tried place the speed test on server with 10G ethernet
and run it on client side at the same network with 1G ethernet
The download speed only keep at (~5XX mbps) while upload speed are ~9XX mbps

Would you please advise if it is normal of download speed result. 
Due to running at TCP??? or other limitation which can be configured.

Thanks

**Comment by adolfintel** [comment]
Write me at dosse91@paranoici.org for troubleshooting
