### ISSUE TITLE
Command line client

### ISSUE THREAD

**Issue by xoro** [adolfintel/speedtest#89]
First I would like to thank you for that really cool piece of software!!!!
**Thanks a lot!**

Is it possible to create an example-cli.html that could be called via curl like this:
```
# curl https://speedtest.example.com/example-cli.html
```
The output could be very simple like:
```
Download: 123.0 Mbps
Upload: 123.0 Mpbs
Ping: 12.0 ms
Jitter: 13.0 ms
```

**Comment by adolfintel** [comment]
No, the test is done client side with Javascript.
If that's what you need, maybe iperf is best for you?

**Comment by Perflyst** [comment]
@xoro In case you are still interested: https://github.com/librespeed/speedtest-cli
