### ISSUE TITLE
No Speed

### ISSUE THREAD

**Issue by juliodiz** [adolfintel/speedtest#95]
Not working. How can i debug? Thanks

<img width="1326" alt="captura de tela 2017-11-17 as 11 43 58" src="https://user-images.githubusercontent.com/13019871/32950215-b4ce2ee4-cb8c-11e7-954c-36484b319e40.png">

**Comment by adolfintel** [comment]
I need more info about your setup, and if possible, an URL to your server so I can test it.
Also, did you read the troubleshooting section of doc.md?

P.S. as I said several times in the project, contact me directly at dosse91@paranoici.org for troubleshooting, otherwise the people who are watching this project will get a bunch of emails.

**Comment by juliodiz** [comment]
Its possible without openssl_random_pseudo_bytes ?
I am using 5.2.3 php

**Comment by adolfintel** [comment]
You can configure the test to use a large file instead of garbage.php.
You can use the garbage.dat linked in the documentation, and edit the example to point it to garbage.dat

**Comment by juliodiz** [comment]
Hello.

I am using 5.2.3 . The problem is openssl_random_pseudo_bytes

Have a solution whiteout this funciona? Because i am using with Zend and
can't change my version php

Julio Diz

2017-11-17 11:51 GMT-02:00 Federico Dossena <notifications@github.com>:

**Comment by adolfintel** [comment]
You're still posting on github if you're replying to the emails. 
Write me directly please, I'll show you how to do it

**Comment by juliodiz** [comment]
Sorry, i saw your message after i post.

"You can configure the test to use a large file instead of garbage.php.
You can use the garbage.dat linked in the documentation, and edit the
example to point it to garbage.dat"

I believe i can't do it, i don't know how to do it

Julio Diz

2017-11-17 11:57 GMT-02:00 Federico Dossena <notifications@github.com>:

**Comment by juliodiz** [comment]
I try $data=decbin(rand(0,1048576));
But not worked

Julio Diz

2017-11-17 12:01 GMT-02:00 julio diz <juliodiz@gmail.com>:

**Comment by adolfintel** [comment]
You're using example-progressBar, right?
At line 143 replace
```
w.postMessage('start');
```
with
```
w.postMessage('start {"url_dl":"garbage.dat"}');
```
and extract this archive where you have your speedtest http://downloads.fdossena.com/geth.php?r=speedtest-bigfile

This should fix your problem with openssl_random_pseudo_bytes
