### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by arkof** [adolfintel/speedtest#96]
Hey
Just wounder if I've done something wrong. Got the speedtest running and everything works fine.
Got 8GB ram on the VM, after first testa i run, the memeory consumption goest up to 13%, after second test its goes to 80-90%. It never seems to go down again after the tests have been run. 
Hosting it on a Windows 2012 with PHP 7.1.12.

**Comment by adolfintel** [comment]
Is this client side?
The XHRs are destroyed, as well as their pointers, so the browser will call the garbage collector when the memory starts to fill.

If it's server side, god helps you, I have no idea how such a simple script can cause a memory leak on the server.

**Comment by arkof** [comment]
Yeah sorry forgot the tell its server-side.
I'll try to look in too it, I'll get back if I find something.

**Comment by adolfintel** [comment]
That is weird. See if you can replicate the issue on a clean system, maybe it's a just a config issue.

**Comment by adolfintel** [comment]
Any news?

**Comment by arkof** [comment]
Yeah sorry. I migrated it to a Linuxserver instead. Works alot better, haven't had time to try to replicate it on a Windowsserver.

**Comment by adolfintel** [comment]
I'm unable to replicate it too so I'll close the issue. If you find out something new let me know
