### ISSUE TITLE
Wrong postMessage value

### ISSUE THREAD

**Issue by rafal1137** [adolfintel/speedtest#98]
Hi 1st of all I want to say I did send email to you about troubleshooting and waited few days without answer so I was forced to post it here.

I did modified few things to meet my needs.
I have custom script that gets my ip its included right bellow style pasted it in one of your examples that I am using

`<script type="text/javascript">
                  var ip2;
                  function requestServerCall(url) {
                    var head = document.head;
                    var script = document.createElement("script");

                    script.setAttribute("src", url);
                head.appendChild(script);
                    head.removeChild(script);
                }

                //Predefined callback function   
                function jsonpCallback(data) {
                ip2 = data.message;
                //alert(data.message); // Response data from the server
                }

                //Send Request to Server
                function sendRequest() {
                    // Edit with your Web Service URL
                    requestServerCall("http://10.1.201.11/speedtest/myService.php?callback=jsonpCallback");
                }   

</script>`

Then postingmessage to worker
w.postMessage('start {"telemetry_level": "basic", "clientIp": "ip2"}');
clientIp var is present in speedtest_worker.min.js
And I did modified getIp function.

`function getIp (done) {
  tlog('getIp')
  if (ipCalled) return; else ipCalled = true // getIp already called?
//  xhr = new XMLHttpRequest()
//  xhr.onload = function () {
//    tlog("IP: "+xhr.responseText)
//    clientIp = xhr.responseText
    tlog("IP: "+settings.clientIp)
    clientIp = settings.clientIp
    done()
// }
//  xhr.onerror = function () {
//    tlog('getIp failed')
//    done()
//  }
//  xhr.open('GET', settings.url_getIp + url_sep(settings.url_getIp) + 'r=' + Math.random(), true)
//  xhr.send()
}`

After Starting test IP Adress gets wrong value

**Comment by adolfintel** [comment]
Hi,
I didn't get your email or I would have replied.

```w.postMessage('start {"telemetry_level": "basic", "clientIp": "ip2"}');```
You're passing the string "ip2" rather than its value, so that's the first problem. Once you've fixed this, you'll have a variable called clientIp inside the settings object in the worker. You can check for this variable to bypass my getIp code.
However, there is a much easier way to do this: simply set ```test_order``` to ```P_D_U```, this will skip my getIp code and you can just display the output from your function in the IP field.
